export interface MockRawTrack {
	durationSeconds: number;
	id: string;
	title: string;
	trackNumber: number;
}

export interface MockRawAlbum {
	albumArtist: string;
	artwork?: string;
	id: string;
	releaseYear?: number;
	title: string;
	tracks: Array<MockRawTrack>;
}

export const mockRawAlbums: Array<MockRawAlbum> = [
	{
		albumArtist: 'Converge',
		artwork: 'https://coverartarchive.org/release/c0c80905-b460-4385-b84d-b068eb14bf5a/front-500',
		id: 'album-1',
		releaseYear: 2001,
		title: 'Jane Doe',
		tracks: [
			{ durationSeconds: 79, id: 'track-1', title: 'Concubine', trackNumber: 1 },
			{ durationSeconds: 185, id: 'track-81', title: 'Fault and Fracture', trackNumber: 2 },
			{ durationSeconds: 258, id: 'track-82', title: 'Distance and Meaning', trackNumber: 3 },
			{ durationSeconds: 272, id: 'track-83', title: 'Hell to Pay', trackNumber: 4 },
			{ durationSeconds: 231, id: 'track-84', title: 'Homewrecker', trackNumber: 5 },
			{ durationSeconds: 133, id: 'track-85', title: 'The Broken Vow', trackNumber: 6 },
			{ durationSeconds: 88, id: 'track-86', title: 'Bitter and Then Some', trackNumber: 7 },
			{ durationSeconds: 241, id: 'track-87', title: 'Heaven in Her Arms', trackNumber: 8 },
			{ durationSeconds: 229, id: 'track-88', title: 'Phoenix in Flight', trackNumber: 9 },
			{ durationSeconds: 42, id: 'track-89', title: 'Phoenix in Flames', trackNumber: 10 },
			{ durationSeconds: 270, id: 'track-234', title: 'Thaw', trackNumber: 11 },
			{ durationSeconds: 694, id: 'track-2', title: 'Jane Doe', trackNumber: 12 },
		],
	},
	{
		albumArtist: 'Converge',
		artwork: 'https://coverartarchive.org/release/84f8ae0e-8d40-409a-adc4-45147c427a3d/front-500',
		id: 'album-2',
		releaseYear: 2009,
		title: 'Axe to Fall',
		tracks: [
			{ durationSeconds: 175, id: 'track-3', title: 'Dark Horse', trackNumber: 1 },
			{ durationSeconds: 159, id: 'track-90', title: 'Reap What You Sow', trackNumber: 2 },
			{ durationSeconds: 101, id: 'track-4', title: 'Axe to Fall', trackNumber: 3 },
			{ durationSeconds: 103, id: 'track-235', title: 'Effigy', trackNumber: 4 },
			{
				durationSeconds: 353,
				id: 'track-236',
				title: 'Worms Will Feed / Rats Will Feast',
				trackNumber: 5,
			},
			{ durationSeconds: 170, id: 'track-237', title: 'Wishing Well', trackNumber: 6 },
			{ durationSeconds: 266, id: 'track-238', title: 'Damages', trackNumber: 7 },
			{ durationSeconds: 107, id: 'track-239', title: 'Losing Battle', trackNumber: 8 },
			{ durationSeconds: 156, id: 'track-240', title: 'Dead Beat', trackNumber: 9 },
			{ durationSeconds: 100, id: 'track-241', title: 'Cutter', trackNumber: 10 },
			{ durationSeconds: 168, id: 'track-242', title: 'Slave Driver', trackNumber: 11 },
			{ durationSeconds: 242, id: 'track-243', title: 'Cruel Bloom', trackNumber: 12 },
			{ durationSeconds: 431, id: 'track-244', title: 'Wretched World', trackNumber: 13 },
		],
	},
	{
		albumArtist: 'Agriculture',
		artwork: 'https://lastfm.freetls.fastly.net/i/u/ar0/303cb80d05626e302dccea9b85eccf2b.jpg',
		id: 'album-3',
		releaseYear: 2025,
		title: 'The Spiritual Sound',
		tracks: [
			{ durationSeconds: 313, id: 'track-5', title: 'My Garden', trackNumber: 1 },
			{ durationSeconds: 235, id: 'track-69', title: 'Flea', trackNumber: 2 },
			{ durationSeconds: 262, id: 'track-70', title: 'Micah (5:15am)', trackNumber: 3 },
			{ durationSeconds: 343, id: 'track-6', title: 'The Weight', trackNumber: 4 },
			{ durationSeconds: 187, id: 'track-327', title: 'Serenity', trackNumber: 5 },
			{ durationSeconds: 29, id: 'track-328', title: 'The Spiritual Sound', trackNumber: 6 },
			{ durationSeconds: 291, id: 'track-329', title: "Dan's Love Song", trackNumber: 7 },
			{ durationSeconds: 383, id: 'track-330', title: 'Bodhidharma', trackNumber: 8 },
			{ durationSeconds: 210, id: 'track-331', title: 'Hallelujah', trackNumber: 9 },
			{ durationSeconds: 389, id: 'track-332', title: 'The Reply', trackNumber: 10 },
		],
	},
	{
		albumArtist: 'Chat Pile',
		artwork: 'https://lastfm.freetls.fastly.net/i/u/ar0/6c099a5ebaa92b345c52de52370cff14.jpg',
		id: 'album-4',
		releaseYear: 2022,
		title: "God's Country",
		tracks: [
			{ durationSeconds: 192, id: 'track-7', title: 'Slaughterhouse', trackNumber: 1 },
			{ durationSeconds: 171, id: 'track-71', title: 'Wicked Puppet Dance', trackNumber: 2 },
			{ durationSeconds: 262, id: 'track-72', title: 'Grimace_Smoking_Weed.jpeg', trackNumber: 3 },
			{ durationSeconds: 208, id: 'track-91', title: 'Tropical Beaches, Inc.', trackNumber: 4 },
			{ durationSeconds: 198, id: 'track-92', title: 'The Mask', trackNumber: 5 },
			{ durationSeconds: 204, id: 'track-93', title: 'Shame', trackNumber: 6 },
			{ durationSeconds: 201, id: 'track-94', title: 'Pamela', trackNumber: 7 },
			{ durationSeconds: 274, id: 'track-8', title: 'Why', trackNumber: 8 },
		],
	},
	{
		albumArtist: 'HEALTH',
		artwork: 'https://lastfm.freetls.fastly.net/i/u/ar0/dbe4b1469b50ae4f91ecaa42f72b619b.jpg',
		id: 'album-5',
		releaseYear: 2023,
		title: 'RAT WARS',
		tracks: [
			{ durationSeconds: 190, id: 'track-73', title: 'RAT WARS', trackNumber: 1 },
			{ durationSeconds: 209, id: 'track-9', title: 'HATEFUL', trackNumber: 2 },
			{ durationSeconds: 232, id: 'track-95', title: 'CHILDREN OF SORROW', trackNumber: 3 },
			{ durationSeconds: 201, id: 'track-74', title: 'CRACK METAL', trackNumber: 4 },
			{ durationSeconds: 215, id: 'track-96', title: 'UNLOVED', trackNumber: 5 },
			{ durationSeconds: 224, id: 'track-10', title: 'DEMIGODS', trackNumber: 6 },
		],
	},
	{
		albumArtist: 'Single Mothers',
		artwork: 'https://lastfm.freetls.fastly.net/i/u/ar0/32a26d741e9547efc7ff9a0df60ab866.jpg',
		id: 'album-6',
		releaseYear: 2014,
		title: 'Negative Qualities',
		tracks: [
			{ durationSeconds: 119, id: 'track-11', title: 'Overdose', trackNumber: 1 },
			{ durationSeconds: 133, id: 'track-97', title: 'Half-Lit (Intro)', trackNumber: 2 },
			{ durationSeconds: 142, id: 'track-75', title: 'Marbles', trackNumber: 3 },
			{ durationSeconds: 136, id: 'track-76', title: 'Ketamine', trackNumber: 4 },
			{ durationSeconds: 146, id: 'track-12', title: 'Half-Lit', trackNumber: 5 },
		],
	},
	{
		albumArtist: 'Converge',
		artwork: 'https://coverartarchive.org/release/78b13e58-ab68-43a5-bfe1-df8407021b6f/front-500',
		id: 'album-7',
		releaseYear: 2004,
		title: 'You Fail Me',
		tracks: [
			{ durationSeconds: 60, id: 'track-13', title: 'First Light', trackNumber: 1 },
			{ durationSeconds: 214, id: 'track-245', title: 'Last Light', trackNumber: 2 },
			{ durationSeconds: 139, id: 'track-246', title: 'Black Cloud', trackNumber: 3 },
			{ durationSeconds: 152, id: 'track-247', title: 'Drop Out', trackNumber: 4 },
			{ durationSeconds: 67, id: 'track-248', title: 'Hope Street', trackNumber: 5 },
			{ durationSeconds: 148, id: 'track-249', title: 'Heartless', trackNumber: 6 },
			{ durationSeconds: 337, id: 'track-250', title: 'You Fail Me', trackNumber: 7 },
			{ durationSeconds: 386, id: 'track-251', title: 'In Her Shadow', trackNumber: 8 },
			{ durationSeconds: 132, id: 'track-14', title: 'Eagles Become Vultures', trackNumber: 9 },
			{ durationSeconds: 153, id: 'track-252', title: 'Wolves at My Door', trackNumber: 10 },
			{ durationSeconds: 128, id: 'track-253', title: 'Death King', trackNumber: 11 },
			{ durationSeconds: 247, id: 'track-254', title: 'In Her Blood', trackNumber: 12 },
			{ durationSeconds: 124, id: 'track-255', title: 'Hanging Moon', trackNumber: 13 },
		],
	},
	{
		albumArtist: 'Converge',
		artwork: 'https://lastfm.freetls.fastly.net/i/u/ar0/92d1aaff5e0b77c06074ba7b309eec88.jpg',
		id: 'album-8',
		releaseYear: 2012,
		title: 'All We Love We Leave Behind',
		tracks: [
			{ durationSeconds: 174, id: 'track-15', title: 'Aimless Arrow', trackNumber: 1 },
			{ durationSeconds: 198, id: 'track-98', title: 'Trespasses', trackNumber: 2 },
			{ durationSeconds: 166, id: 'track-99', title: 'Tender Abuse', trackNumber: 3 },
			{ durationSeconds: 200, id: 'track-16', title: 'Sadness Comes Home', trackNumber: 4 },
		],
	},
	{
		albumArtist: 'Converge',
		artwork: 'https://coverartarchive.org/release/1af78661-4d13-4d2c-bad8-b4dc3c6ef1a8/front-500',
		id: 'album-9',
		releaseYear: 1996,
		title: 'Petitioning the Empty Sky',
		tracks: [
			{ durationSeconds: 425, id: 'track-17', title: 'The Saddest Day', trackNumber: 1 },
			{ durationSeconds: 140, id: 'track-100', title: 'Forsaken', trackNumber: 2 },
			{ durationSeconds: 109, id: 'track-101', title: 'Albatross', trackNumber: 3 },
			{ durationSeconds: 186, id: 'track-102', title: 'Dead', trackNumber: 4 },
			{ durationSeconds: 254, id: 'track-256', title: 'Shingles', trackNumber: 5 },
			{ durationSeconds: 71, id: 'track-257', title: 'Buried but Breathing', trackNumber: 6 },
			{
				durationSeconds: 320,
				id: 'track-258',
				title: 'Farewell Note to This City',
				trackNumber: 7,
			},
			{ durationSeconds: 237, id: 'track-18', title: 'Color Me Blood Red', trackNumber: 8 },
			{ durationSeconds: 164, id: 'track-259', title: 'For You (live)', trackNumber: 9 },
			{ durationSeconds: 340, id: 'track-260', title: 'Antithesis (live)', trackNumber: 10 },
			{ durationSeconds: 426, id: 'track-261', title: 'Homesong (live)', trackNumber: 11 },
			{
				durationSeconds: 183,
				id: 'track-262',
				title: 'Love as Arson (alternate version)',
				trackNumber: 12,
			},
		],
	},
	{
		albumArtist: 'Converge',
		artwork: 'https://coverartarchive.org/release/db28c9b5-d24a-45cd-9223-32bde6f0a9b7/front-500',
		id: 'album-10',
		releaseYear: 1998,
		title: 'When Forever Comes Crashing',
		tracks: [
			{ durationSeconds: 204, id: 'track-263', title: 'My Unsaid Everything', trackNumber: 1 },
			{
				durationSeconds: 257,
				id: 'track-19',
				title: 'The High Cost of Playing God',
				trackNumber: 2,
			},
			{ durationSeconds: 260, id: 'track-103', title: 'In Harms Way', trackNumber: 3 },
			{ durationSeconds: 250, id: 'track-104', title: 'Conduit', trackNumber: 4 },
			{
				durationSeconds: 234,
				id: 'track-105',
				title: 'The Lowest Common Denominator',
				trackNumber: 5,
			},
			{ durationSeconds: 141, id: 'track-106', title: 'Towing Jehovah', trackNumber: 6 },
			{
				durationSeconds: 194,
				id: 'track-264',
				title: 'When Forever Comes Crashing',
				trackNumber: 7,
			},
			{ durationSeconds: 140, id: 'track-265', title: 'Ten Cents', trackNumber: 8 },
			{ durationSeconds: 227, id: 'track-266', title: 'Year of the Swine', trackNumber: 9 },
			{ durationSeconds: 262, id: 'track-20', title: 'Letterbomb', trackNumber: 10 },
			{ durationSeconds: 203, id: 'track-267', title: 'Love as Arson', trackNumber: 11 },
			{
				durationSeconds: 89,
				id: 'track-268',
				title: 'Bitter and Then Some (demo version)',
				trackNumber: 12,
			},
		],
	},
	{
		albumArtist: 'Converge',
		artwork: 'https://coverartarchive.org/release/2c5274b5-c468-4378-8347-8d270635d06d/front-500',
		id: 'album-11',
		releaseYear: 2017,
		title: 'The Dusk in Us',
		tracks: [
			{ durationSeconds: 200, id: 'track-21', title: 'A Single Tear', trackNumber: 1 },
			{ durationSeconds: 135, id: 'track-109', title: 'Eye of the Quarrel', trackNumber: 2 },
			{ durationSeconds: 223, id: 'track-110', title: 'Under Duress', trackNumber: 3 },
			{ durationSeconds: 173, id: 'track-111', title: 'Arkhipov Calm', trackNumber: 4 },
			{ durationSeconds: 144, id: 'track-112', title: 'I Can Tell You About Pain', trackNumber: 5 },
			{ durationSeconds: 443, id: 'track-22', title: 'The Dusk in Us', trackNumber: 6 },
			{ durationSeconds: 149, id: 'track-190', title: 'Wildlife', trackNumber: 7 },
			{ durationSeconds: 181, id: 'track-191', title: 'Murk & Marrow', trackNumber: 8 },
			{ durationSeconds: 214, id: 'track-192', title: 'Trigger', trackNumber: 9 },
			{ durationSeconds: 107, id: 'track-193', title: 'Broken by Light', trackNumber: 10 },
			{ durationSeconds: 76, id: 'track-194', title: 'Cannibals', trackNumber: 11 },
			{
				durationSeconds: 283,
				id: 'track-195',
				title: 'Thousands of Miles Between Us',
				trackNumber: 12,
			},
			{ durationSeconds: 273, id: 'track-196', title: 'Reptilian', trackNumber: 13 },
		],
	},
	{
		albumArtist: 'Converge',
		artwork: 'https://coverartarchive.org/release/ec7ee58e-671c-4705-97fb-ef25a75e9acb/front-500',
		id: 'album-12',
		releaseYear: 2021,
		title: 'Bloodmoon: I',
		tracks: [
			{ durationSeconds: 471, id: 'track-23', title: 'Blood Moon', trackNumber: 1 },
			{ durationSeconds: 329, id: 'track-269', title: 'Viscera of Men', trackNumber: 2 },
			{ durationSeconds: 368, id: 'track-270', title: 'Coil', trackNumber: 3 },
			{ durationSeconds: 278, id: 'track-24', title: 'Flower Moon', trackNumber: 4 },
			{ durationSeconds: 252, id: 'track-271', title: 'Tongues Playing Dead', trackNumber: 5 },
			{ durationSeconds: 201, id: 'track-272', title: 'Lord of Liars', trackNumber: 6 },
			{ durationSeconds: 243, id: 'track-273', title: 'Failure Forever', trackNumber: 7 },
			{ durationSeconds: 348, id: 'track-274', title: "Scorpion's Sting", trackNumber: 8 },
			{ durationSeconds: 419, id: 'track-275', title: 'Daimon', trackNumber: 9 },
			{ durationSeconds: 407, id: 'track-276', title: 'Crimson Stone', trackNumber: 10 },
			{ durationSeconds: 211, id: 'track-277', title: 'Blood Dawn', trackNumber: 11 },
		],
	},
	{
		albumArtist: 'Touche Amore',
		artwork: 'https://coverartarchive.org/release/f70ae983-dfb5-4be3-99a5-9f18c7366700/front-500',
		id: 'album-13',
		releaseYear: 2016,
		title: 'Stage Four',
		tracks: [
			{ durationSeconds: 214, id: 'track-25', title: 'Flowers and You', trackNumber: 1 },
			{ durationSeconds: 208, id: 'track-115', title: 'New Halloween', trackNumber: 2 },
			{ durationSeconds: 192, id: 'track-116', title: 'Rapture', trackNumber: 3 },
			{ durationSeconds: 131, id: 'track-117', title: 'Displacement', trackNumber: 4 },
			{ durationSeconds: 220, id: 'track-278', title: 'Benediction', trackNumber: 5 },
			{ durationSeconds: 92, id: 'track-279', title: 'Eight Seconds', trackNumber: 6 },
			{ durationSeconds: 147, id: 'track-26', title: 'Palm Dreams', trackNumber: 7 },
			{ durationSeconds: 116, id: 'track-280', title: 'Softer Spoken', trackNumber: 8 },
			{ durationSeconds: 168, id: 'track-281', title: 'Posing Holy', trackNumber: 9 },
			{ durationSeconds: 233, id: 'track-282', title: 'Water Damage', trackNumber: 10 },
			{ durationSeconds: 233, id: 'track-283', title: 'Skyscraper', trackNumber: 11 },
		],
	},
	{
		albumArtist: 'Touche Amore',
		artwork: 'https://coverartarchive.org/release/4eade845-9fea-4b4e-89e9-878e0da55f37/front-500',
		id: 'album-14',
		releaseYear: 2020,
		title: 'Lament',
		tracks: [
			{ durationSeconds: 170, id: 'track-27', title: 'Come Heroine', trackNumber: 1 },
			{ durationSeconds: 200, id: 'track-118', title: 'Lament', trackNumber: 2 },
			{ durationSeconds: 168, id: 'track-119', title: 'Feign', trackNumber: 3 },
			{ durationSeconds: 183, id: 'track-120', title: 'Reminders', trackNumber: 4 },
			{ durationSeconds: 302, id: 'track-28', title: 'Limelight', trackNumber: 5 },
			{ durationSeconds: 136, id: 'track-284', title: 'Exit Row', trackNumber: 6 },
			{ durationSeconds: 176, id: 'track-285', title: 'Savoring', trackNumber: 7 },
			{ durationSeconds: 181, id: 'track-286', title: 'A Broadcast', trackNumber: 8 },
			{ durationSeconds: 207, id: 'track-287', title: "I'll Be Your Host", trackNumber: 9 },
			{ durationSeconds: 211, id: 'track-288', title: 'Deflector', trackNumber: 10 },
			{ durationSeconds: 218, id: 'track-289', title: 'A Forecast', trackNumber: 11 },
		],
	},
	{
		albumArtist: 'The Armed',
		artwork: 'https://coverartarchive.org/release/1736ec94-5839-4d12-9b49-31cdca467905/front-500',
		id: 'album-15',
		releaseYear: 2021,
		title: 'ULTRAPOP',
		tracks: [
			{ durationSeconds: 163, id: 'track-29', title: 'ULTRAPOP', trackNumber: 1 },
			{ durationSeconds: 185, id: 'track-30', title: 'ALL FUTURES', trackNumber: 2 },
			{ durationSeconds: 150, id: 'track-290', title: 'MASUNAGA VAPORS', trackNumber: 3 },
			{ durationSeconds: 187, id: 'track-291', title: 'A LIFE SO WONDERFUL', trackNumber: 4 },
			{ durationSeconds: 173, id: 'track-292', title: 'AN ITERATION', trackNumber: 5 },
			{ durationSeconds: 197, id: 'track-293', title: 'BIG SHELL', trackNumber: 6 },
			{ durationSeconds: 272, id: 'track-294', title: 'AVERAGE DEATH', trackNumber: 7 },
			{ durationSeconds: 226, id: 'track-295', title: 'FAITH IN MEDICATION', trackNumber: 8 },
			{ durationSeconds: 176, id: 'track-296', title: 'WHERE MAN KNOWS WANT', trackNumber: 9 },
			{ durationSeconds: 219, id: 'track-297', title: 'REAL FOLK BLUES', trackNumber: 10 },
			{ durationSeconds: 225, id: 'track-298', title: 'BAD SELECTION', trackNumber: 11 },
			{
				durationSeconds: 158,
				id: 'track-299',
				title: 'THE MUSIC BECOMES A SKULL',
				trackNumber: 12,
			},
		],
	},
	{
		albumArtist: 'The Armed',
		artwork: 'https://coverartarchive.org/release/f6d10643-b0f2-40b5-ad0f-955676b70ec5/front-500',
		id: 'album-16',
		releaseYear: 2023,
		title: 'Perfect Saviors',
		tracks: [
			{ durationSeconds: 165, id: 'track-31', title: 'Sport of Measure', trackNumber: 1 },
			{ durationSeconds: 189, id: 'track-121', title: 'FKA World', trackNumber: 2 },
			{ durationSeconds: 181, id: 'track-122', title: 'Clone', trackNumber: 3 },
			{ durationSeconds: 228, id: 'track-123', title: 'Modern Vanity', trackNumber: 4 },
			{ durationSeconds: 230, id: 'track-32', title: "Everything's Glitter", trackNumber: 5 },
			{ durationSeconds: 251, id: 'track-197', title: 'Burned Mind', trackNumber: 6 },
			{ durationSeconds: 206, id: 'track-198', title: 'Sport of Form', trackNumber: 7 },
			{ durationSeconds: 155, id: 'track-199', title: 'Patient Mind', trackNumber: 8 },
			{
				durationSeconds: 212,
				id: 'track-200',
				title: 'Vatican Under Construction',
				trackNumber: 9,
			},
			{ durationSeconds: 180, id: 'track-201', title: 'Liar 2', trackNumber: 10 },
			{ durationSeconds: 204, id: 'track-202', title: 'In Heaven', trackNumber: 11 },
			{ durationSeconds: 297, id: 'track-203', title: 'Public Grieving', trackNumber: 12 },
		],
	},
	{
		albumArtist: 'Birds In Row',
		artwork: 'https://coverartarchive.org/release/910b544a-99aa-45a7-925f-b5e2a712b481/front-500',
		id: 'album-17',
		releaseYear: 2022,
		title: 'Gris Klein',
		tracks: [
			{ durationSeconds: 145, id: 'track-33', title: 'Water Wings', trackNumber: 1 },
			{ durationSeconds: 144, id: 'track-125', title: 'Daltonians', trackNumber: 2 },
			{ durationSeconds: 197, id: 'track-129', title: 'Confettis', trackNumber: 3 },
			{ durationSeconds: 398, id: 'track-127', title: 'Noah', trackNumber: 4 },
			{ durationSeconds: 192, id: 'track-130', title: 'Cathedrals', trackNumber: 5 },
			{ durationSeconds: 205, id: 'track-126', title: 'Nympheas', trackNumber: 6 },
			{ durationSeconds: 203, id: 'track-204', title: 'Grisaille', trackNumber: 7 },
			{ durationSeconds: 364, id: 'track-34', title: "Trompe l'oeil", trackNumber: 8 },
			{ durationSeconds: 185, id: 'track-205', title: 'Rodin', trackNumber: 9 },
			{ durationSeconds: 182, id: 'track-206', title: 'Winter, Yet', trackNumber: 10 },
			{ durationSeconds: 287, id: 'track-128', title: 'Secession', trackNumber: 11 },
		],
	},
	{
		albumArtist: 'Birds In Row',
		artwork: 'https://coverartarchive.org/release/f235904a-0494-4d7f-becb-051e51765385/front-500',
		id: 'album-18',
		releaseYear: 2018,
		title: 'We Already Lost the World',
		tracks: [
			{
				durationSeconds: 191,
				id: 'track-131',
				title: "We Count So We Don't Have to Listen",
				trackNumber: 1,
			},
			{ durationSeconds: 167, id: 'track-132', title: 'Love Is Political', trackNumber: 2 },
			{ durationSeconds: 292, id: 'track-207', title: 'We vs. Us', trackNumber: 3 },
			{
				durationSeconds: 309,
				id: 'track-208',
				title: 'Remember Us Better Than We Are',
				trackNumber: 4,
			},
			{ durationSeconds: 183, id: 'track-36', title: "I Don't Dance", trackNumber: 5 },
			{ durationSeconds: 199, id: 'track-35', title: '15-38', trackNumber: 6 },
			{ durationSeconds: 98, id: 'track-209', title: 'Triste Sire', trackNumber: 7 },
			{ durationSeconds: 267, id: 'track-210', title: 'Morning', trackNumber: 8 },
			{ durationSeconds: 351, id: 'track-134', title: 'Fossils', trackNumber: 9 },
		],
	},
	{
		albumArtist: 'Carly Rae Jepsen',
		artwork: 'https://lastfm.freetls.fastly.net/i/u/ar0/f8e8eb1fab348cff53beb038f0a05210.jpg',
		id: 'album-19',
		releaseYear: 2015,
		title: 'Emotion',
		tracks: [
			{ durationSeconds: 250, id: 'track-37', title: 'Run Away with Me', trackNumber: 1 },
			{ durationSeconds: 238, id: 'track-135', title: 'Emotion', trackNumber: 2 },
			{ durationSeconds: 246, id: 'track-136', title: 'I Really Like You', trackNumber: 3 },
			{ durationSeconds: 231, id: 'track-137', title: 'Gimmie Love', trackNumber: 4 },
			{ durationSeconds: 234, id: 'track-138', title: 'All That', trackNumber: 5 },
			{ durationSeconds: 228, id: 'track-139', title: 'Boy Problems', trackNumber: 6 },
			{
				durationSeconds: 242,
				id: 'track-140',
				title: 'Making the Most of the Night',
				trackNumber: 7,
			},
			{ durationSeconds: 250, id: 'track-38', title: 'Your Type', trackNumber: 8 },
		],
	},
	{
		albumArtist: 'Carly Rae Jepsen',
		artwork: 'https://coverartarchive.org/release/f034293b-6ba6-4fc3-9e27-bbee22256b0d/front-500',
		id: 'album-20',
		releaseYear: 2022,
		title: 'The Loneliest Time',
		tracks: [
			{ durationSeconds: 168, id: 'track-39', title: 'Surrender My Heart', trackNumber: 1 },
			{ durationSeconds: 149, id: 'track-141', title: 'Joshua Tree', trackNumber: 2 },
			{ durationSeconds: 173, id: 'track-142', title: 'Talking to Yourself', trackNumber: 3 },
			{ durationSeconds: 179, id: 'track-143', title: 'Far Away', trackNumber: 4 },
			{ durationSeconds: 136, id: 'track-144', title: 'Sideways', trackNumber: 5 },
			{ durationSeconds: 149, id: 'track-145', title: 'Beach House', trackNumber: 6 },
			{ durationSeconds: 195, id: 'track-146', title: 'Bends', trackNumber: 7 },
			{ durationSeconds: 225, id: 'track-147', title: 'Western Wind', trackNumber: 8 },
			{ durationSeconds: 219, id: 'track-211', title: 'So Nice', trackNumber: 9 },
			{ durationSeconds: 193, id: 'track-212', title: 'Bad Thing Twice', trackNumber: 10 },
			{ durationSeconds: 199, id: 'track-213', title: 'Shooting Star', trackNumber: 11 },
			{
				durationSeconds: 284,
				id: 'track-148',
				title: 'Go Find Yourself or Whatever',
				trackNumber: 12,
			},
			{ durationSeconds: 274, id: 'track-40', title: 'The Loneliest Time', trackNumber: 13 },
		],
	},
	{
		albumArtist: 'Venturing',
		artwork: 'https://lastfm.freetls.fastly.net/i/u/ar0/9373642d1f9fc218700f8ff915974988.jpg',
		id: 'album-21',
		releaseYear: 2023,
		title: 'Ghostholding',
		tracks: [
			{ durationSeconds: 217, id: 'track-41', title: 'Recoil', trackNumber: 1 },
			{ durationSeconds: 231, id: 'track-77', title: 'Wallflower', trackNumber: 2 },
			{ durationSeconds: 205, id: 'track-78', title: 'Liminal Room', trackNumber: 3 },
			{ durationSeconds: 214, id: 'track-149', title: 'Pale Hallway', trackNumber: 4 },
			{ durationSeconds: 286, id: 'track-42', title: 'No Ending', trackNumber: 5 },
		],
	},
	{
		albumArtist: 'Petey USA',
		artwork: 'https://coverartarchive.org/release/949fcc15-15ac-4a70-ad8b-2b5894cdee97/front-500',
		id: 'album-23',
		releaseYear: 2021,
		title: 'Lean Into Life',
		tracks: [
			{ durationSeconds: 276, id: 'track-214', title: 'California', trackNumber: 1 },
			{ durationSeconds: 176, id: 'track-46', title: 'Apple TV Remote', trackNumber: 2 },
			{ durationSeconds: 262, id: 'track-215', title: 'Pitch a Fit!', trackNumber: 3 },
			{ durationSeconds: 237, id: 'track-216', title: "DON'T TELL THE BOYS", trackNumber: 4 },
			{ durationSeconds: 282, id: 'track-217', title: 'Microwave Dinner', trackNumber: 5 },
			{ durationSeconds: 117, id: 'track-218', title: 'Oh Nice', trackNumber: 6 },
			{ durationSeconds: 165, id: 'track-219', title: 'We Go On Walks', trackNumber: 7 },
			{
				durationSeconds: 301,
				id: 'track-220',
				title: "We Don't Need to Talk About It",
				trackNumber: 8,
			},
			{ durationSeconds: 158, id: 'track-221', title: 'Hey Man', trackNumber: 9 },
			{ durationSeconds: 211, id: 'track-222', title: 'Comfort in the Clutter', trackNumber: 10 },
			{ durationSeconds: 327, id: 'track-45', title: 'Lean Into Life', trackNumber: 11 },
			{ durationSeconds: 126, id: 'track-223', title: 'Tell the Boys', trackNumber: 12 },
			{ durationSeconds: 202, id: 'track-224', title: 'Perfect Teeth', trackNumber: 13 },
		],
	},
	{
		albumArtist: 'Petey USA',
		artwork: 'https://lastfm.freetls.fastly.net/i/u/ar0/26abd405dd4e783afe5fb601ff3ff64f.jpg',
		id: 'album-24',
		releaseYear: 2023,
		title: 'USA',
		tracks: [
			{ durationSeconds: 94, id: 'track-155', title: 'Bags Theme', trackNumber: 1 },
			{ durationSeconds: 172, id: 'track-333', title: "I'll Wait", trackNumber: 2 },
			{
				durationSeconds: 233,
				id: 'track-156',
				title: 'I Tried to Draw a Straight Line',
				trackNumber: 3,
			},
			{ durationSeconds: 182, id: 'track-48', title: 'Home Alone House', trackNumber: 4 },
			{ durationSeconds: 214, id: 'track-334', title: 'Skip This One', trackNumber: 5 },
			{ durationSeconds: 197, id: 'track-157', title: "Did I Mention I'm Sorry", trackNumber: 6 },
			{ durationSeconds: 144, id: 'track-335', title: 'Birds of a Feather', trackNumber: 7 },
			{ durationSeconds: 214, id: 'track-336', title: 'Living Like This', trackNumber: 8 },
			{ durationSeconds: 300, id: 'track-47', title: 'Family of Six', trackNumber: 9 },
			{ durationSeconds: 243, id: 'track-337', title: 'The Freedom to Fuck Off', trackNumber: 10 },
			{ durationSeconds: 273, id: 'track-338', title: 'How Bout That', trackNumber: 11 },
			{ durationSeconds: 305, id: 'track-339', title: 'Goodnight Nurse', trackNumber: 12 },
		],
	},
	{
		albumArtist: 'Jane Remover',
		artwork: 'https://coverartarchive.org/release/f765dd4e-6d1b-466d-901e-ba9827391796/front-500',
		id: 'album-25',
		releaseYear: 2021,
		title: 'Frailty',
		tracks: [
			{ durationSeconds: 181, id: 'track-159', title: 'Goldfish', trackNumber: 1 },
			{ durationSeconds: 255, id: 'track-160', title: 'Your Clothes', trackNumber: 2 },
			{ durationSeconds: 234, id: 'track-164', title: 'Misplace', trackNumber: 3 },
			{ durationSeconds: 221, id: 'track-161', title: 'Pretender', trackNumber: 4 },
			{ durationSeconds: 298, id: 'track-49', title: 'Search Party', trackNumber: 5 },
			{ durationSeconds: 151, id: 'track-162', title: 'Buzzcut, Daisy', trackNumber: 6 },
			{ durationSeconds: 346, id: 'track-50', title: 'Movies For Guys', trackNumber: 7 },
			{ durationSeconds: 367, id: 'track-163', title: 'Kodak Moment', trackNumber: 8 },
			{ durationSeconds: 209, id: 'track-165', title: 'Can You Tell?', trackNumber: 9 },
			{ durationSeconds: 225, id: 'track-340', title: 'How To Lie', trackNumber: 10 },
			{ durationSeconds: 377, id: 'track-341', title: 'Champ', trackNumber: 11 },
			{
				durationSeconds: 234,
				id: 'track-342',
				title: "Eyes Off the Wheel, I'm a Star",
				trackNumber: 12,
			},
			{ durationSeconds: 333, id: 'track-343', title: "Let's Go Home", trackNumber: 13 },
		],
	},
	{
		albumArtist: 'Jane Remover',
		artwork: 'https://coverartarchive.org/release/b91d5017-c197-46e6-82b8-3663ea3fae59/front-500',
		id: 'album-26',
		releaseYear: 2023,
		title: 'Census Designated',
		tracks: [
			{ durationSeconds: 344, id: 'track-166', title: 'Cage Girl / Camgirl', trackNumber: 1 },
			{ durationSeconds: 311, id: 'track-51', title: 'Lips', trackNumber: 2 },
			{ durationSeconds: 294, id: 'track-168', title: 'Fling', trackNumber: 3 },
			{ durationSeconds: 276, id: 'track-170', title: 'Holding a Leech', trackNumber: 4 },
			{ durationSeconds: 361, id: 'track-171', title: 'Backseat Girl', trackNumber: 5 },
			{ durationSeconds: 443, id: 'track-167', title: 'Idling Somewhere', trackNumber: 6 },
			{ durationSeconds: 391, id: 'track-344', title: 'Always Have Always Will', trackNumber: 7 },
			{ durationSeconds: 361, id: 'track-169', title: 'Census Designated', trackNumber: 8 },
			{ durationSeconds: 523, id: 'track-52', title: 'Video', trackNumber: 9 },
			{
				durationSeconds: 387,
				id: 'track-345',
				title: 'Contingency Song (Album Version)',
				trackNumber: 10,
			},
		],
	},
	{
		albumArtist: 'Liturgy',
		artwork: 'https://coverartarchive.org/release/4177877e-0adf-4a2e-921b-caf7198130f5/front-500',
		id: 'album-27',
		releaseYear: 2023,
		title: '93696',
		tracks: [
			{ durationSeconds: 451, id: 'track-53', title: '93696', trackNumber: 1 },
			{ durationSeconds: 349, id: 'track-54', title: 'Angel of Sovereignty', trackNumber: 2 },
		],
	},
	{
		albumArtist: 'Liturgy',
		artwork: 'https://coverartarchive.org/release/345ad36c-adb4-404e-95fc-ccffcfba10e0/front-500',
		id: 'album-28',
		releaseYear: 2020,
		title: 'Origin of the Alimonies',
		tracks: [
			{ durationSeconds: 315, id: 'track-55', title: 'Murmur of Chalices', trackNumber: 1 },
			{ durationSeconds: 328, id: 'track-172', title: 'Acqua', trackNumber: 2 },
			{ durationSeconds: 341, id: 'track-173', title: 'Orrery', trackNumber: 3 },
			{ durationSeconds: 372, id: 'track-56', title: 'Angel of Hierarchy', trackNumber: 4 },
		],
	},
	{
		albumArtist: 'Beecher',
		artwork: 'https://coverartarchive.org/release/109a6c4d-cfb0-41d5-983f-23b59bf5b5c4/front-500',
		id: 'album-29',
		releaseYear: 2001,
		title: 'Breaking the Fourth Wall',
		tracks: [
			{ durationSeconds: 173, id: 'track-57', title: 'Let Them Drown', trackNumber: 1 },
			{ durationSeconds: 229, id: 'track-174', title: 'Dead for Weeks', trackNumber: 2 },
			{ durationSeconds: 234, id: 'track-175', title: 'Burning Surface', trackNumber: 3 },
			{ durationSeconds: 143, id: 'track-176', title: 'Arrow Flies', trackNumber: 4 },
			{ durationSeconds: 81, id: 'track-177', title: 'Mercury Switch', trackNumber: 5 },
			{ durationSeconds: 123, id: 'track-178', title: 'Floating Point', trackNumber: 6 },
			{ durationSeconds: 238, id: 'track-58', title: 'The Only One I Know', trackNumber: 7 },
			{ durationSeconds: 205, id: 'track-225', title: 'Red Diesel', trackNumber: 8 },
			{ durationSeconds: 143, id: 'track-226', title: 'Cabin Boy Jumped Ship', trackNumber: 9 },
			{ durationSeconds: 351, id: 'track-227', title: 'An Important Letter', trackNumber: 10 },
			{
				durationSeconds: 866,
				id: 'track-228',
				title: 'Ladder Theory / Crack Fiend',
				trackNumber: 11,
			},
		],
	},
	{
		albumArtist: 'Beecher',
		artwork: 'https://coverartarchive.org/release/3bf0feb5-6d6b-4eff-872d-4ac771210b9e/front-500',
		id: 'album-30',
		releaseYear: 2003,
		title: 'This Elegy, His Autopsy',
		tracks: [
			{
				durationSeconds: 156,
				id: 'track-179',
				title: "It's Good Weather for Black Leather",
				trackNumber: 1,
			},
			{ durationSeconds: 124, id: 'track-59', title: 'Function! Function!', trackNumber: 2 },
			{
				durationSeconds: 64,
				id: 'track-180',
				title: 'The Womaniser & the Alcoholic',
				trackNumber: 3,
			},
			{ durationSeconds: 103, id: 'track-181', title: 'Knight the Arsonist', trackNumber: 4 },
			{ durationSeconds: 246, id: 'track-182', title: 'Not Guilty', trackNumber: 5 },
			{
				durationSeconds: 242,
				id: 'track-183',
				title: 'And on the Day That He Became a Human Plumb-Line',
				trackNumber: 6,
			},
			{
				durationSeconds: 256,
				id: 'track-184',
				title: 'Psycho Galvanic Skin Response',
				trackNumber: 7,
			},
			{ durationSeconds: 161, id: 'track-60', title: 'Man the Traps', trackNumber: 8 },
			{ durationSeconds: 134, id: 'track-229', title: 'Brown Eyes (No Name)', trackNumber: 9 },
			{ durationSeconds: 82, id: 'track-230', title: 'The Biting Cold', trackNumber: 10 },
			{
				durationSeconds: 247,
				id: 'track-231',
				title: "I Won't Miss or Be Missed",
				trackNumber: 11,
			},
			{ durationSeconds: 152, id: 'track-232', title: 'Happiness', trackNumber: 12 },
			{ durationSeconds: 505, id: 'track-233', title: 'Reach Up to the Gods', trackNumber: 13 },
		],
	},
	{
		albumArtist: 'Charli XCX',
		artwork: 'https://lastfm.freetls.fastly.net/i/u/ar0/b00527c6ae0cd1d4c9bf3706b130ad56.jpg',
		id: 'album-31',
		releaseYear: 2024,
		title: 'Brat',
		tracks: [
			{ durationSeconds: 131, id: 'track-61', title: '360', trackNumber: 1 },
			{ durationSeconds: 145, id: 'track-62', title: 'Von dutch', trackNumber: 2 },
		],
	},
	{
		albumArtist: 'Charli XCX',
		artwork: 'https://coverartarchive.org/release/2c951df6-cbe4-4239-9a43-e54e8a50a468/front-500',
		id: 'album-32',
		releaseYear: 2022,
		title: 'Crash',
		tracks: [
			{ durationSeconds: 151, id: 'track-63', title: 'Crash', trackNumber: 1 },
			{ durationSeconds: 201, id: 'track-300', title: 'New Shapes', trackNumber: 2 },
			{ durationSeconds: 137, id: 'track-64', title: 'Good Ones', trackNumber: 3 },
			{ durationSeconds: 189, id: 'track-301', title: 'Constant Repeat', trackNumber: 4 },
			{ durationSeconds: 168, id: 'track-302', title: 'Beg for You', trackNumber: 5 },
			{ durationSeconds: 147, id: 'track-303', title: 'Move Me', trackNumber: 6 },
			{ durationSeconds: 160, id: 'track-304', title: 'Baby', trackNumber: 7 },
			{ durationSeconds: 237, id: 'track-305', title: 'Lightning', trackNumber: 8 },
			{ durationSeconds: 183, id: 'track-306', title: 'Every Rule', trackNumber: 9 },
			{ durationSeconds: 139, id: 'track-307', title: 'Yuck', trackNumber: 10 },
			{ durationSeconds: 146, id: 'track-308', title: 'Used to Know Me', trackNumber: 11 },
			{ durationSeconds: 195, id: 'track-309', title: 'Twice', trackNumber: 12 },
			{ durationSeconds: 194, id: 'track-310', title: 'Selfish Girl', trackNumber: 13 },
			{
				durationSeconds: 157,
				id: 'track-311',
				title: 'How Can I Not Know What I Need Right Now',
				trackNumber: 14,
			},
			{ durationSeconds: 161, id: 'track-312', title: 'Sorry If I Hurt You', trackNumber: 15 },
			{ durationSeconds: 184, id: 'track-313', title: 'What You Think About Me', trackNumber: 16 },
		],
	},
	{
		albumArtist: 'Chelsea Wolfe',
		artwork: 'https://coverartarchive.org/release/2a8eaa8c-beea-43d4-b8bf-671812291546/front-500',
		id: 'album-33',
		releaseYear: 2017,
		title: 'Hiss Spun',
		tracks: [
			{ durationSeconds: 329, id: 'track-65', title: 'Spun', trackNumber: 1 },
			{ durationSeconds: 259, id: 'track-66', title: '16 Psyche', trackNumber: 2 },
			{ durationSeconds: 183, id: 'track-185', title: 'Vex', trackNumber: 3 },
			{ durationSeconds: 74, id: 'track-314', title: 'Strain', trackNumber: 4 },
			{ durationSeconds: 362, id: 'track-315', title: 'The Culling', trackNumber: 5 },
			{ durationSeconds: 293, id: 'track-316', title: 'Particle Flux', trackNumber: 6 },
			{ durationSeconds: 368, id: 'track-317', title: 'Twin Fawn', trackNumber: 7 },
			{ durationSeconds: 171, id: 'track-318', title: 'Offering', trackNumber: 8 },
			{ durationSeconds: 262, id: 'track-319', title: 'Static Hum', trackNumber: 9 },
			{ durationSeconds: 115, id: 'track-320', title: 'Welt', trackNumber: 10 },
			{ durationSeconds: 305, id: 'track-321', title: 'Two Spirit', trackNumber: 11 },
			{ durationSeconds: 184, id: 'track-322', title: 'Scrape', trackNumber: 12 },
		],
	},
	{
		albumArtist: 'Chelsea Wolfe',
		artwork: 'https://coverartarchive.org/release/33922aab-40f8-4d43-8d1c-7693562f784e/front-500',
		id: 'album-34',
		releaseYear: 2024,
		title: 'She Reaches Out to She Reaches Out to She',
		tracks: [
			{
				durationSeconds: 241,
				id: 'track-67',
				title: 'Whispers in the Echo Chamber',
				trackNumber: 1,
			},
			{ durationSeconds: 263, id: 'track-186', title: 'House of Self-Undoing', trackNumber: 2 },
			{ durationSeconds: 266, id: 'track-187', title: 'Everything Turns Blue', trackNumber: 3 },
			{ durationSeconds: 248, id: 'track-68', title: 'Tunnel Lights', trackNumber: 4 },
			{ durationSeconds: 292, id: 'track-323', title: 'The Liminal', trackNumber: 5 },
			{ durationSeconds: 274, id: 'track-324', title: 'Eyes Like Nightshade', trackNumber: 6 },
			{ durationSeconds: 264, id: 'track-325', title: 'Salt', trackNumber: 7 },
			{ durationSeconds: 207, id: 'track-189', title: 'Unseen World', trackNumber: 8 },
			{ durationSeconds: 250, id: 'track-326', title: 'Place in the Sun', trackNumber: 9 },
			{ durationSeconds: 274, id: 'track-188', title: 'Dusk', trackNumber: 10 },
		],
	},
];
