export interface MockRawTrack {
	durationSeconds: number;
	id: string;
	title: string;
	trackNumber: number;
}

export interface MockRawAlbum {
	albumArtist: string;
	artwork?: string;
	bio?: string;
	id: string;
	releaseYear?: number;
	title: string;
	tracks: Array<MockRawTrack>;
}

export const mockRawAlbums: Array<MockRawAlbum> = [
	{
		albumArtist: 'Converge',
		artwork: 'https://coverartarchive.org/release/c0c80905-b460-4385-b84d-b068eb14bf5a/front-500',
		bio: "Jane Doe is Converge's fourth studio album, released in 2001 on Equal Vision Records. Conceived as a breakup album, it channels raw emotional devastation into some of the most ferocious music of its era. The title track closes the record at over eleven minutes — an anomaly in the band's typically compact catalog — and remains one of hardcore's most harrowing pieces of music. The album's fractured, chaotic production by Kurt Ballou became a blueprint for an entire generation of heavy bands.",
		id: 'album-1',
		releaseYear: 2001,
		title: 'Jane Doe',
		tracks: [
			{ durationSeconds: 79, id: 'track-1', title: 'Concubine', trackNumber: 1 },
			{ durationSeconds: 185, id: 'track-81', title: 'Fault and Fracture', trackNumber: 2 },
			{ durationSeconds: 258, id: 'track-82', title: 'Distance and Meaning', trackNumber: 3 },
			{ durationSeconds: 272, id: 'track-83', title: 'Hell to Pay', trackNumber: 4 },
			{ durationSeconds: 231, id: 'track-84', title: 'Homewrecker', trackNumber: 5 },
			{ durationSeconds: 133, id: 'track-85', title: 'The Broken Vow', trackNumber: 6 },
			{ durationSeconds: 88, id: 'track-86', title: 'Bitter and Then Some', trackNumber: 7 },
			{ durationSeconds: 241, id: 'track-87', title: 'Heaven in Her Arms', trackNumber: 8 },
			{ durationSeconds: 229, id: 'track-88', title: 'Phoenix in Flight', trackNumber: 9 },
			{ durationSeconds: 42, id: 'track-89', title: 'Phoenix in Flames', trackNumber: 10 },
			{ durationSeconds: 270, id: 'track-234', title: 'Thaw', trackNumber: 11 },
			{ durationSeconds: 694, id: 'track-2', title: 'Jane Doe', trackNumber: 12 },
		],
	},
	{
		albumArtist: 'Converge',
		artwork: 'https://coverartarchive.org/release/84f8ae0e-8d40-409a-adc4-45147c427a3d/front-500',
		bio: "Axe to Fall is Converge's seventh studio album, released October 20, 2009 through Epitaph Records and produced by guitarist Kurt Ballou, with artwork by vocalist Jacob Bannon. It is a collaborative album featuring guest musicians from Cave In, Neurosis, and The Red Chord among others. The album peaked at number 74 on the Billboard 200 and is noted as the band's most commercially accessible release to date.",
		id: 'album-2',
		releaseYear: 2009,
		title: 'Axe to Fall',
		tracks: [
			{ durationSeconds: 175, id: 'track-3', title: 'Dark Horse', trackNumber: 1 },
			{ durationSeconds: 159, id: 'track-90', title: 'Reap What You Sow', trackNumber: 2 },
			{ durationSeconds: 101, id: 'track-4', title: 'Axe to Fall', trackNumber: 3 },
			{ durationSeconds: 103, id: 'track-235', title: 'Effigy', trackNumber: 4 },
			{
				durationSeconds: 353,
				id: 'track-236',
				title: 'Worms Will Feed / Rats Will Feast',
				trackNumber: 5,
			},
			{ durationSeconds: 170, id: 'track-237', title: 'Wishing Well', trackNumber: 6 },
			{ durationSeconds: 266, id: 'track-238', title: 'Damages', trackNumber: 7 },
			{ durationSeconds: 107, id: 'track-239', title: 'Losing Battle', trackNumber: 8 },
			{ durationSeconds: 156, id: 'track-240', title: 'Dead Beat', trackNumber: 9 },
			{ durationSeconds: 100, id: 'track-241', title: 'Cutter', trackNumber: 10 },
			{ durationSeconds: 168, id: 'track-242', title: 'Slave Driver', trackNumber: 11 },
			{ durationSeconds: 242, id: 'track-243', title: 'Cruel Bloom', trackNumber: 12 },
			{ durationSeconds: 431, id: 'track-244', title: 'Wretched World', trackNumber: 13 },
		],
	},
	{
		albumArtist: 'Agriculture',
		artwork: 'https://lastfm.freetls.fastly.net/i/u/ar0/303cb80d05626e302dccea9b85eccf2b.jpg',
		bio: "The Spiritual Sound is Agriculture's second album, released in 2025. Building on the devotional atmosphere of their debut, the record pushes deeper into themes of Eastern philosophy, spiritual longing, and transcendence, while retaining the cascading tremolo-driven black metal that defined their sound. It was met with widespread critical acclaim as one of the year's most ambitious heavy records.",
		id: 'album-3',
		releaseYear: 2025,
		title: 'The Spiritual Sound',
		tracks: [
			{ durationSeconds: 313, id: 'track-5', title: 'My Garden', trackNumber: 1 },
			{ durationSeconds: 235, id: 'track-69', title: 'Flea', trackNumber: 2 },
			{ durationSeconds: 262, id: 'track-70', title: 'Micah (5:15am)', trackNumber: 3 },
			{ durationSeconds: 343, id: 'track-6', title: 'The Weight', trackNumber: 4 },
			{ durationSeconds: 187, id: 'track-327', title: 'Serenity', trackNumber: 5 },
			{ durationSeconds: 29, id: 'track-328', title: 'The Spiritual Sound', trackNumber: 6 },
			{ durationSeconds: 291, id: 'track-329', title: "Dan's Love Song", trackNumber: 7 },
			{ durationSeconds: 383, id: 'track-330', title: 'Bodhidharma', trackNumber: 8 },
			{ durationSeconds: 210, id: 'track-331', title: 'Hallelujah', trackNumber: 9 },
			{ durationSeconds: 389, id: 'track-332', title: 'The Reply', trackNumber: 10 },
		],
	},
	{
		albumArtist: 'Chat Pile',
		artwork: 'https://lastfm.freetls.fastly.net/i/u/ar0/6c099a5ebaa92b345c52de52370cff14.jpg',
		bio: "God's Country is the debut studio album by Chat Pile, released July 29, 2022 through The Flenser. The album achieved notable critical acclaim, peaking at No. 21 on the Apple Music Chart and earning a Best New Music designation from Pitchfork. Its eight tracks drag listeners through a harrowing portrait of Midwestern poverty, violence, and despair, delivered with Raygun Busch's uniquely conversational and terrifying vocal style.",
		id: 'album-4',
		releaseYear: 2022,
		title: "God's Country",
		tracks: [
			{ durationSeconds: 192, id: 'track-7', title: 'Slaughterhouse', trackNumber: 1 },
			{ durationSeconds: 171, id: 'track-71', title: 'Wicked Puppet Dance', trackNumber: 2 },
			{ durationSeconds: 262, id: 'track-72', title: 'Grimace_Smoking_Weed.jpeg', trackNumber: 3 },
			{ durationSeconds: 208, id: 'track-91', title: 'Tropical Beaches, Inc.', trackNumber: 4 },
			{ durationSeconds: 198, id: 'track-92', title: 'The Mask', trackNumber: 5 },
			{ durationSeconds: 204, id: 'track-93', title: 'Shame', trackNumber: 6 },
			{ durationSeconds: 201, id: 'track-94', title: 'Pamela', trackNumber: 7 },
			{ durationSeconds: 274, id: 'track-8', title: 'Why', trackNumber: 8 },
		],
	},
	{
		albumArtist: 'HEALTH',
		artwork: 'https://lastfm.freetls.fastly.net/i/u/ar0/dbe4b1469b50ae4f91ecaa42f72b619b.jpg',
		bio: "RAT WARS is HEALTH's sixth studio album, released December 7, 2023 through Loma Vista Recordings and produced by Stint. The album blends metal, electronic, and industrial elements while exploring darker, more personal themes, and features collaborations with SIERRA VEINS, Willie Adler of Lamb of God, and members of Youth Code and Street Sects. It received generally favorable critical reception, with reviewers praising its cinematic intensity and sonic harshness.",
		id: 'album-5',
		releaseYear: 2023,
		title: 'RAT WARS',
		tracks: [
			{ durationSeconds: 190, id: 'track-73', title: 'RAT WARS', trackNumber: 1 },
			{ durationSeconds: 209, id: 'track-9', title: 'HATEFUL', trackNumber: 2 },
			{ durationSeconds: 232, id: 'track-95', title: 'CHILDREN OF SORROW', trackNumber: 3 },
			{ durationSeconds: 201, id: 'track-74', title: 'CRACK METAL', trackNumber: 4 },
			{ durationSeconds: 215, id: 'track-96', title: 'UNLOVED', trackNumber: 5 },
			{ durationSeconds: 224, id: 'track-10', title: 'DEMIGODS', trackNumber: 6 },
		],
	},
	{
		albumArtist: 'Single Mothers',
		artwork: 'https://lastfm.freetls.fastly.net/i/u/ar0/32a26d741e9547efc7ff9a0df60ab866.jpg',
		bio: "Negative Qualities is Single Mothers' debut full-length album, released in 2014. The record distills the band's caustic live energy into a tight collection of songs about addiction, debt, and self-destruction. Short and relentless, it established the London, Ontario group as one of the most vital acts in Canadian hardcore.",
		id: 'album-6',
		releaseYear: 2014,
		title: 'Negative Qualities',
		tracks: [
			{ durationSeconds: 119, id: 'track-11', title: 'Overdose', trackNumber: 1 },
			{ durationSeconds: 133, id: 'track-97', title: 'Half-Lit (Intro)', trackNumber: 2 },
			{ durationSeconds: 142, id: 'track-75', title: 'Marbles', trackNumber: 3 },
			{ durationSeconds: 136, id: 'track-76', title: 'Ketamine', trackNumber: 4 },
			{ durationSeconds: 146, id: 'track-12', title: 'Half-Lit', trackNumber: 5 },
		],
	},
	{
		albumArtist: 'Converge',
		artwork: 'https://coverartarchive.org/release/78b13e58-ab68-43a5-bfe1-df8407021b6f/front-500',
		bio: "You Fail Me is Converge's fifth studio album, released September 20, 2004, marking their debut on Epitaph Records after leaving Equal Vision. Recorded and produced by Kurt Ballou, the album is darker and more atmospheric than Jane Doe, channelling exhaustion and loss rather than raw fury. It charted at 171 on the Billboard 200, the band's first major chart appearance.",
		id: 'album-7',
		releaseYear: 2004,
		title: 'You Fail Me',
		tracks: [
			{ durationSeconds: 60, id: 'track-13', title: 'First Light', trackNumber: 1 },
			{ durationSeconds: 214, id: 'track-245', title: 'Last Light', trackNumber: 2 },
			{ durationSeconds: 139, id: 'track-246', title: 'Black Cloud', trackNumber: 3 },
			{ durationSeconds: 152, id: 'track-247', title: 'Drop Out', trackNumber: 4 },
			{ durationSeconds: 67, id: 'track-248', title: 'Hope Street', trackNumber: 5 },
			{ durationSeconds: 148, id: 'track-249', title: 'Heartless', trackNumber: 6 },
			{ durationSeconds: 337, id: 'track-250', title: 'You Fail Me', trackNumber: 7 },
			{ durationSeconds: 386, id: 'track-251', title: 'In Her Shadow', trackNumber: 8 },
			{ durationSeconds: 132, id: 'track-14', title: 'Eagles Become Vultures', trackNumber: 9 },
			{ durationSeconds: 153, id: 'track-252', title: 'Wolves at My Door', trackNumber: 10 },
			{ durationSeconds: 128, id: 'track-253', title: 'Death King', trackNumber: 11 },
			{ durationSeconds: 247, id: 'track-254', title: 'In Her Blood', trackNumber: 12 },
			{ durationSeconds: 124, id: 'track-255', title: 'Hanging Moon', trackNumber: 13 },
		],
	},
	{
		albumArtist: 'Converge',
		artwork: 'https://lastfm.freetls.fastly.net/i/u/ar0/92d1aaff5e0b77c06074ba7b309eec88.jpg',
		bio: 'All We Love We Leave Behind is Converge\'s eighth studio album, released October 9, 2012 through Epitaph Records with a vinyl edition via Deathwish Inc. The 17-track album includes the single "Aimless Arrow," which received a music video directed by Max Moore. It is considered among the band\'s most compositionally expansive releases, balancing speed, melody, and dissonance across its sprawling runtime.',
		id: 'album-8',
		releaseYear: 2012,
		title: 'All We Love We Leave Behind',
		tracks: [
			{ durationSeconds: 174, id: 'track-15', title: 'Aimless Arrow', trackNumber: 1 },
			{ durationSeconds: 198, id: 'track-98', title: 'Trespasses', trackNumber: 2 },
			{ durationSeconds: 166, id: 'track-99', title: 'Tender Abuse', trackNumber: 3 },
			{ durationSeconds: 200, id: 'track-16', title: 'Sadness Comes Home', trackNumber: 4 },
		],
	},
	{
		albumArtist: 'Converge',
		artwork: 'https://coverartarchive.org/release/1af78661-4d13-4d2c-bad8-b4dc3c6ef1a8/front-500',
		bio: 'Petitioning the Empty Sky is a Converge compilation originally released in 1996 through Ferret Music as a 7" EP, later reissued in expanded form on Equal Vision Records in 1998. The full-length version features twelve songs recorded at different times, including both studio and live recordings. It documents the band\'s early melodic hardcore roots before the visceral turn that would define Jane Doe.',
		id: 'album-9',
		releaseYear: 1996,
		title: 'Petitioning the Empty Sky',
		tracks: [
			{ durationSeconds: 425, id: 'track-17', title: 'The Saddest Day', trackNumber: 1 },
			{ durationSeconds: 140, id: 'track-100', title: 'Forsaken', trackNumber: 2 },
			{ durationSeconds: 109, id: 'track-101', title: 'Albatross', trackNumber: 3 },
			{ durationSeconds: 186, id: 'track-102', title: 'Dead', trackNumber: 4 },
			{ durationSeconds: 254, id: 'track-256', title: 'Shingles', trackNumber: 5 },
			{ durationSeconds: 71, id: 'track-257', title: 'Buried but Breathing', trackNumber: 6 },
			{
				durationSeconds: 320,
				id: 'track-258',
				title: 'Farewell Note to This City',
				trackNumber: 7,
			},
			{ durationSeconds: 237, id: 'track-18', title: 'Color Me Blood Red', trackNumber: 8 },
			{ durationSeconds: 164, id: 'track-259', title: 'For You (live)', trackNumber: 9 },
			{ durationSeconds: 340, id: 'track-260', title: 'Antithesis (live)', trackNumber: 10 },
			{ durationSeconds: 426, id: 'track-261', title: 'Homesong (live)', trackNumber: 11 },
			{
				durationSeconds: 183,
				id: 'track-262',
				title: 'Love as Arson (alternate version)',
				trackNumber: 12,
			},
		],
	},
	{
		albumArtist: 'Converge',
		artwork: 'https://coverartarchive.org/release/db28c9b5-d24a-45cd-9223-32bde6f0a9b7/front-500',
		bio: 'When Forever Comes Crashing is Converge\'s third album, recorded at God City Studio and released in 1998. The band collaborated with producer Steve Austin of Today Is the Day, who also provided backup vocals on "The Lowest Common Denominator." The album received a reissue in 2005 with bonus material, and stands as a key bridge between the band\'s early melodic hardcore and the brutalist intensity of Jane Doe.',
		id: 'album-10',
		releaseYear: 1998,
		title: 'When Forever Comes Crashing',
		tracks: [
			{ durationSeconds: 204, id: 'track-263', title: 'My Unsaid Everything', trackNumber: 1 },
			{
				durationSeconds: 257,
				id: 'track-19',
				title: 'The High Cost of Playing God',
				trackNumber: 2,
			},
			{ durationSeconds: 260, id: 'track-103', title: 'In Harms Way', trackNumber: 3 },
			{ durationSeconds: 250, id: 'track-104', title: 'Conduit', trackNumber: 4 },
			{
				durationSeconds: 234,
				id: 'track-105',
				title: 'The Lowest Common Denominator',
				trackNumber: 5,
			},
			{ durationSeconds: 141, id: 'track-106', title: 'Towing Jehovah', trackNumber: 6 },
			{
				durationSeconds: 194,
				id: 'track-264',
				title: 'When Forever Comes Crashing',
				trackNumber: 7,
			},
			{ durationSeconds: 140, id: 'track-265', title: 'Ten Cents', trackNumber: 8 },
			{ durationSeconds: 227, id: 'track-266', title: 'Year of the Swine', trackNumber: 9 },
			{ durationSeconds: 262, id: 'track-20', title: 'Letterbomb', trackNumber: 10 },
			{ durationSeconds: 203, id: 'track-267', title: 'Love as Arson', trackNumber: 11 },
			{
				durationSeconds: 89,
				id: 'track-268',
				title: 'Bitter and Then Some (demo version)',
				trackNumber: 12,
			},
		],
	},
	{
		albumArtist: 'Converge',
		artwork: 'https://coverartarchive.org/release/2c5274b5-c468-4378-8347-8d270635d06d/front-500',
		bio: "The Dusk in Us is Converge's ninth studio album, released November 3, 2017 through Epitaph Records and Deathwish Inc., produced by guitarist Kurt Ballou with artwork by vocalist Jacob Bannon. Written during a period of personal upheaval for several band members, the album finds unexpected tenderness alongside the band's signature ferocity. The title track runs over seven minutes — one of the longest pieces in their catalog.",
		id: 'album-11',
		releaseYear: 2017,
		title: 'The Dusk in Us',
		tracks: [
			{ durationSeconds: 200, id: 'track-21', title: 'A Single Tear', trackNumber: 1 },
			{ durationSeconds: 135, id: 'track-109', title: 'Eye of the Quarrel', trackNumber: 2 },
			{ durationSeconds: 223, id: 'track-110', title: 'Under Duress', trackNumber: 3 },
			{ durationSeconds: 173, id: 'track-111', title: 'Arkhipov Calm', trackNumber: 4 },
			{ durationSeconds: 144, id: 'track-112', title: 'I Can Tell You About Pain', trackNumber: 5 },
			{ durationSeconds: 443, id: 'track-22', title: 'The Dusk in Us', trackNumber: 6 },
			{ durationSeconds: 149, id: 'track-190', title: 'Wildlife', trackNumber: 7 },
			{ durationSeconds: 181, id: 'track-191', title: 'Murk & Marrow', trackNumber: 8 },
			{ durationSeconds: 214, id: 'track-192', title: 'Trigger', trackNumber: 9 },
			{ durationSeconds: 107, id: 'track-193', title: 'Broken by Light', trackNumber: 10 },
			{ durationSeconds: 76, id: 'track-194', title: 'Cannibals', trackNumber: 11 },
			{
				durationSeconds: 283,
				id: 'track-195',
				title: 'Thousands of Miles Between Us',
				trackNumber: 12,
			},
			{ durationSeconds: 273, id: 'track-196', title: 'Reptilian', trackNumber: 13 },
		],
	},
	{
		albumArtist: 'Converge',
		artwork: 'https://coverartarchive.org/release/ec7ee58e-671c-4705-97fb-ef25a75e9acb/front-500',
		bio: "Bloodmoon: I is a collaborative album by Converge and Chelsea Wolfe, with contributions from Aaron Turner of Isis and Ben Chisholm and Stephen Brodsky. Released November 19, 2021 through Epitaph Records and Sargent House, the record is slower and more atmospheric than typical Converge material, drawing on doom, folk, and art rock. Chelsea Wolfe's voice weaves through the eleven tracks as an equal creative force rather than a guest.",
		id: 'album-12',
		releaseYear: 2021,
		title: 'Bloodmoon: I',
		tracks: [
			{ durationSeconds: 471, id: 'track-23', title: 'Blood Moon', trackNumber: 1 },
			{ durationSeconds: 329, id: 'track-269', title: 'Viscera of Men', trackNumber: 2 },
			{ durationSeconds: 368, id: 'track-270', title: 'Coil', trackNumber: 3 },
			{ durationSeconds: 278, id: 'track-24', title: 'Flower Moon', trackNumber: 4 },
			{ durationSeconds: 252, id: 'track-271', title: 'Tongues Playing Dead', trackNumber: 5 },
			{ durationSeconds: 201, id: 'track-272', title: 'Lord of Liars', trackNumber: 6 },
			{ durationSeconds: 243, id: 'track-273', title: 'Failure Forever', trackNumber: 7 },
			{ durationSeconds: 348, id: 'track-274', title: "Scorpion's Sting", trackNumber: 8 },
			{ durationSeconds: 419, id: 'track-275', title: 'Daimon', trackNumber: 9 },
			{ durationSeconds: 407, id: 'track-276', title: 'Crimson Stone', trackNumber: 10 },
			{ durationSeconds: 211, id: 'track-277', title: 'Blood Dawn', trackNumber: 11 },
		],
	},
	{
		albumArtist: 'Touche Amore',
		artwork: 'https://coverartarchive.org/release/f70ae983-dfb5-4be3-99a5-9f18c7366700/front-500',
		bio: "Stage Four is Touché Amoré's fourth studio album, released September 16, 2016 through Epitaph Records, written by vocalist Jeremy Bolm as a tribute to his mother following her death from cancer. Each of the album's eleven tracks takes a different perspective on grief — from hospital visits to estate sales — making it one of the most direct and devastating records in post-hardcore. The Julien Baker–featured \"Skyscraper\" became one of the band's most celebrated songs.",
		id: 'album-13',
		releaseYear: 2016,
		title: 'Stage Four',
		tracks: [
			{ durationSeconds: 214, id: 'track-25', title: 'Flowers and You', trackNumber: 1 },
			{ durationSeconds: 208, id: 'track-115', title: 'New Halloween', trackNumber: 2 },
			{ durationSeconds: 192, id: 'track-116', title: 'Rapture', trackNumber: 3 },
			{ durationSeconds: 131, id: 'track-117', title: 'Displacement', trackNumber: 4 },
			{ durationSeconds: 220, id: 'track-278', title: 'Benediction', trackNumber: 5 },
			{ durationSeconds: 92, id: 'track-279', title: 'Eight Seconds', trackNumber: 6 },
			{ durationSeconds: 147, id: 'track-26', title: 'Palm Dreams', trackNumber: 7 },
			{ durationSeconds: 116, id: 'track-280', title: 'Softer Spoken', trackNumber: 8 },
			{ durationSeconds: 168, id: 'track-281', title: 'Posing Holy', trackNumber: 9 },
			{ durationSeconds: 233, id: 'track-282', title: 'Water Damage', trackNumber: 10 },
			{ durationSeconds: 233, id: 'track-283', title: 'Skyscraper', trackNumber: 11 },
		],
	},
	{
		albumArtist: 'Touche Amore',
		artwork: 'https://coverartarchive.org/release/4eade845-9fea-4b4e-89e9-878e0da55f37/front-500',
		bio: "Lament is Touché Amoré's fifth studio album, released October 9, 2020 through Epitaph Records, following the deeply personal Stage Four. Produced by Ross Robinson — known for his work with Korn, Slipknot, and At the Drive-In — it is the band's most sonically intense record, with Robinson's raw, room-filling production style pushing the group's dynamic range to its limits. Thematically it grapples with survival, burnout, and the aftermath of grief.",
		id: 'album-14',
		releaseYear: 2020,
		title: 'Lament',
		tracks: [
			{ durationSeconds: 170, id: 'track-27', title: 'Come Heroine', trackNumber: 1 },
			{ durationSeconds: 200, id: 'track-118', title: 'Lament', trackNumber: 2 },
			{ durationSeconds: 168, id: 'track-119', title: 'Feign', trackNumber: 3 },
			{ durationSeconds: 183, id: 'track-120', title: 'Reminders', trackNumber: 4 },
			{ durationSeconds: 302, id: 'track-28', title: 'Limelight', trackNumber: 5 },
			{ durationSeconds: 136, id: 'track-284', title: 'Exit Row', trackNumber: 6 },
			{ durationSeconds: 176, id: 'track-285', title: 'Savoring', trackNumber: 7 },
			{ durationSeconds: 181, id: 'track-286', title: 'A Broadcast', trackNumber: 8 },
			{ durationSeconds: 207, id: 'track-287', title: "I'll Be Your Host", trackNumber: 9 },
			{ durationSeconds: 211, id: 'track-288', title: 'Deflector', trackNumber: 10 },
			{ durationSeconds: 218, id: 'track-289', title: 'A Forecast', trackNumber: 11 },
		],
	},
	{
		albumArtist: 'The Armed',
		artwork: 'https://coverartarchive.org/release/1736ec94-5839-4d12-9b49-31cdca467905/front-500',
		bio: "ULTRAPOP is The Armed's fourth studio album, released April 16, 2021 through Sargent House. A maximalist collision of hardcore, pop, and noise, the album deliberately overloads the listener with competing hooks, distortion, and melody. Mixed by Kurt Ballou, it arrived with an elaborate fictional mythology and an anonymous cast, challenging conventional notions of authorship in heavy music.",
		id: 'album-15',
		releaseYear: 2021,
		title: 'ULTRAPOP',
		tracks: [
			{ durationSeconds: 163, id: 'track-29', title: 'ULTRAPOP', trackNumber: 1 },
			{ durationSeconds: 185, id: 'track-30', title: 'ALL FUTURES', trackNumber: 2 },
			{ durationSeconds: 150, id: 'track-290', title: 'MASUNAGA VAPORS', trackNumber: 3 },
			{ durationSeconds: 187, id: 'track-291', title: 'A LIFE SO WONDERFUL', trackNumber: 4 },
			{ durationSeconds: 173, id: 'track-292', title: 'AN ITERATION', trackNumber: 5 },
			{ durationSeconds: 197, id: 'track-293', title: 'BIG SHELL', trackNumber: 6 },
			{ durationSeconds: 272, id: 'track-294', title: 'AVERAGE DEATH', trackNumber: 7 },
			{ durationSeconds: 226, id: 'track-295', title: 'FAITH IN MEDICATION', trackNumber: 8 },
			{ durationSeconds: 176, id: 'track-296', title: 'WHERE MAN KNOWS WANT', trackNumber: 9 },
			{ durationSeconds: 219, id: 'track-297', title: 'REAL FOLK BLUES', trackNumber: 10 },
			{ durationSeconds: 225, id: 'track-298', title: 'BAD SELECTION', trackNumber: 11 },
			{
				durationSeconds: 158,
				id: 'track-299',
				title: 'THE MUSIC BECOMES A SKULL',
				trackNumber: 12,
			},
		],
	},
	{
		albumArtist: 'The Armed',
		artwork: 'https://coverartarchive.org/release/f6d10643-b0f2-40b5-ad0f-955676b70ec5/front-500',
		bio: "Perfect Saviors is The Armed's fifth studio album, released August 25, 2023 through Sargent House. Refining the maximalist pop-meets-hardcore formula of ULTRAPOP, the record is tighter and more melodically focused, leaning into the paradox of brutality and beauty the band has made their trademark. It was accompanied by an elaborate multimedia rollout including a fictional documentary.",
		id: 'album-16',
		releaseYear: 2023,
		title: 'Perfect Saviors',
		tracks: [
			{ durationSeconds: 165, id: 'track-31', title: 'Sport of Measure', trackNumber: 1 },
			{ durationSeconds: 189, id: 'track-121', title: 'FKA World', trackNumber: 2 },
			{ durationSeconds: 181, id: 'track-122', title: 'Clone', trackNumber: 3 },
			{ durationSeconds: 228, id: 'track-123', title: 'Modern Vanity', trackNumber: 4 },
			{ durationSeconds: 230, id: 'track-32', title: "Everything's Glitter", trackNumber: 5 },
			{ durationSeconds: 251, id: 'track-197', title: 'Burned Mind', trackNumber: 6 },
			{ durationSeconds: 206, id: 'track-198', title: 'Sport of Form', trackNumber: 7 },
			{ durationSeconds: 155, id: 'track-199', title: 'Patient Mind', trackNumber: 8 },
			{
				durationSeconds: 212,
				id: 'track-200',
				title: 'Vatican Under Construction',
				trackNumber: 9,
			},
			{ durationSeconds: 180, id: 'track-201', title: 'Liar 2', trackNumber: 10 },
			{ durationSeconds: 204, id: 'track-202', title: 'In Heaven', trackNumber: 11 },
			{ durationSeconds: 297, id: 'track-203', title: 'Public Grieving', trackNumber: 12 },
		],
	},
	{
		albumArtist: 'Birds In Row',
		artwork: 'https://coverartarchive.org/release/910b544a-99aa-45a7-925f-b5e2a712b481/front-500',
		bio: "Gris Klein is Birds in Row's third studio album, released in 2022 on Cult of Luna's Red Creek label — their first major label release. Named after a shade of grey, the album takes art and colour as its conceptual framework, with track titles referencing artists, movements, and French idioms. It is their most melodically ambitious record to date, stretching their post-hardcore intensity toward more expansive, atmospheric songwriting.",
		id: 'album-17',
		releaseYear: 2022,
		title: 'Gris Klein',
		tracks: [
			{ durationSeconds: 145, id: 'track-33', title: 'Water Wings', trackNumber: 1 },
			{ durationSeconds: 144, id: 'track-125', title: 'Daltonians', trackNumber: 2 },
			{ durationSeconds: 197, id: 'track-129', title: 'Confettis', trackNumber: 3 },
			{ durationSeconds: 398, id: 'track-127', title: 'Noah', trackNumber: 4 },
			{ durationSeconds: 192, id: 'track-130', title: 'Cathedrals', trackNumber: 5 },
			{ durationSeconds: 205, id: 'track-126', title: 'Nympheas', trackNumber: 6 },
			{ durationSeconds: 203, id: 'track-204', title: 'Grisaille', trackNumber: 7 },
			{ durationSeconds: 364, id: 'track-34', title: "Trompe l'oeil", trackNumber: 8 },
			{ durationSeconds: 185, id: 'track-205', title: 'Rodin', trackNumber: 9 },
			{ durationSeconds: 182, id: 'track-206', title: 'Winter, Yet', trackNumber: 10 },
			{ durationSeconds: 287, id: 'track-128', title: 'Secession', trackNumber: 11 },
		],
	},
	{
		albumArtist: 'Birds In Row',
		artwork: 'https://coverartarchive.org/release/f235904a-0494-4d7f-becb-051e51765385/front-500',
		bio: "We Already Lost the World is Birds in Row's second studio album, released in 2018. More politically charged than their debut, the record channels collective dread and systemic disillusionment through their characteristically raw screamo and post-hardcore sound. It earned them recognition beyond the European underground and stands as one of the decade's most underrated heavy albums.",
		id: 'album-18',
		releaseYear: 2018,
		title: 'We Already Lost the World',
		tracks: [
			{
				durationSeconds: 191,
				id: 'track-131',
				title: "We Count So We Don't Have to Listen",
				trackNumber: 1,
			},
			{ durationSeconds: 167, id: 'track-132', title: 'Love Is Political', trackNumber: 2 },
			{ durationSeconds: 292, id: 'track-207', title: 'We vs. Us', trackNumber: 3 },
			{
				durationSeconds: 309,
				id: 'track-208',
				title: 'Remember Us Better Than We Are',
				trackNumber: 4,
			},
			{ durationSeconds: 183, id: 'track-36', title: "I Don't Dance", trackNumber: 5 },
			{ durationSeconds: 199, id: 'track-35', title: '15-38', trackNumber: 6 },
			{ durationSeconds: 98, id: 'track-209', title: 'Triste Sire', trackNumber: 7 },
			{ durationSeconds: 267, id: 'track-210', title: 'Morning', trackNumber: 8 },
			{ durationSeconds: 351, id: 'track-134', title: 'Fossils', trackNumber: 9 },
		],
	},
	{
		albumArtist: 'Carly Rae Jepsen',
		artwork: 'https://lastfm.freetls.fastly.net/i/u/ar0/f8e8eb1fab348cff53beb038f0a05210.jpg',
		bio: "Emotion is Carly Rae Jepsen's third studio album, released in 2015, representing a stylistic shift toward synth-pop drawing inspiration from 1980s music and alternative styles. Features collaborations with prominent producers and artists including Sia, Dev Hynes, and members of The Cardigans, moving away from the bubblegum pop sound of her previous work. Despite modest initial sales, the album developed one of pop music's most devoted cult followings and is now widely considered a modern classic of the genre.",
		id: 'album-19',
		releaseYear: 2015,
		title: 'Emotion',
		tracks: [
			{ durationSeconds: 250, id: 'track-37', title: 'Run Away with Me', trackNumber: 1 },
			{ durationSeconds: 238, id: 'track-135', title: 'Emotion', trackNumber: 2 },
			{ durationSeconds: 246, id: 'track-136', title: 'I Really Like You', trackNumber: 3 },
			{ durationSeconds: 231, id: 'track-137', title: 'Gimmie Love', trackNumber: 4 },
			{ durationSeconds: 234, id: 'track-138', title: 'All That', trackNumber: 5 },
			{ durationSeconds: 228, id: 'track-139', title: 'Boy Problems', trackNumber: 6 },
			{
				durationSeconds: 242,
				id: 'track-140',
				title: 'Making the Most of the Night',
				trackNumber: 7,
			},
			{ durationSeconds: 250, id: 'track-38', title: 'Your Type', trackNumber: 8 },
		],
	},
	{
		albumArtist: 'Carly Rae Jepsen',
		artwork: 'https://coverartarchive.org/release/f034293b-6ba6-4fc3-9e27-bbee22256b0d/front-500',
		bio: "The Loneliest Time is Carly Rae Jepsen's sixth studio album, released October 21, 2022. Recorded during pandemic lockdown over Zoom collaborations with Tavish Crowe, the album draws inspiration from 80s pop, 70s folk, funk, and disco with a more introspective focus on self-reflection. It was praised for broadening her emotional range while retaining the irresistible melodic instincts that made Emotion a cult touchstone.",
		id: 'album-20',
		releaseYear: 2022,
		title: 'The Loneliest Time',
		tracks: [
			{ durationSeconds: 168, id: 'track-39', title: 'Surrender My Heart', trackNumber: 1 },
			{ durationSeconds: 149, id: 'track-141', title: 'Joshua Tree', trackNumber: 2 },
			{ durationSeconds: 173, id: 'track-142', title: 'Talking to Yourself', trackNumber: 3 },
			{ durationSeconds: 179, id: 'track-143', title: 'Far Away', trackNumber: 4 },
			{ durationSeconds: 136, id: 'track-144', title: 'Sideways', trackNumber: 5 },
			{ durationSeconds: 149, id: 'track-145', title: 'Beach House', trackNumber: 6 },
			{ durationSeconds: 195, id: 'track-146', title: 'Bends', trackNumber: 7 },
			{ durationSeconds: 225, id: 'track-147', title: 'Western Wind', trackNumber: 8 },
			{ durationSeconds: 219, id: 'track-211', title: 'So Nice', trackNumber: 9 },
			{ durationSeconds: 193, id: 'track-212', title: 'Bad Thing Twice', trackNumber: 10 },
			{ durationSeconds: 199, id: 'track-213', title: 'Shooting Star', trackNumber: 11 },
			{
				durationSeconds: 284,
				id: 'track-148',
				title: 'Go Find Yourself or Whatever',
				trackNumber: 12,
			},
			{ durationSeconds: 274, id: 'track-40', title: 'The Loneliest Time', trackNumber: 13 },
		],
	},
	{
		albumArtist: 'Venturing',
		artwork: 'https://lastfm.freetls.fastly.net/i/u/ar0/9373642d1f9fc218700f8ff915974988.jpg',
		bio: "Ghostholding is the debut album from Venturing, the alternative rock project of Jane Remover, released in 2023. Originally packaged with an elaborate fiction of a lost 1990s South Dakota band, that backstory was quietly retired upon release. The album channels 90s indie and shoegaze influences into an emotionally raw collection that stands apart from Jane Remover's electronic solo work.",
		id: 'album-21',
		releaseYear: 2023,
		title: 'Ghostholding',
		tracks: [
			{ durationSeconds: 217, id: 'track-41', title: 'Recoil', trackNumber: 1 },
			{ durationSeconds: 231, id: 'track-77', title: 'Wallflower', trackNumber: 2 },
			{ durationSeconds: 205, id: 'track-78', title: 'Liminal Room', trackNumber: 3 },
			{ durationSeconds: 214, id: 'track-149', title: 'Pale Hallway', trackNumber: 4 },
			{ durationSeconds: 286, id: 'track-42', title: 'No Ending', trackNumber: 5 },
		],
	},
	{
		albumArtist: 'Petey USA',
		artwork: 'https://coverartarchive.org/release/949fcc15-15ac-4a70-ad8b-2b5894cdee97/front-500',
		bio: 'Lean Into Life is Petey USA\'s debut full-length album, released in 2021. Blending confessional indie pop with dry humor and a bedroom production aesthetic, the record established his voice as one of the most distinctive in DIY singer-songwriter circles. Songs like "Apple TV Remote" and the title track balance self-deprecation with genuine emotional sincerity.',
		id: 'album-23',
		releaseYear: 2021,
		title: 'Lean Into Life',
		tracks: [
			{ durationSeconds: 276, id: 'track-214', title: 'California', trackNumber: 1 },
			{ durationSeconds: 176, id: 'track-46', title: 'Apple TV Remote', trackNumber: 2 },
			{ durationSeconds: 262, id: 'track-215', title: 'Pitch a Fit!', trackNumber: 3 },
			{ durationSeconds: 237, id: 'track-216', title: "DON'T TELL THE BOYS", trackNumber: 4 },
			{ durationSeconds: 282, id: 'track-217', title: 'Microwave Dinner', trackNumber: 5 },
			{ durationSeconds: 117, id: 'track-218', title: 'Oh Nice', trackNumber: 6 },
			{ durationSeconds: 165, id: 'track-219', title: 'We Go On Walks', trackNumber: 7 },
			{
				durationSeconds: 301,
				id: 'track-220',
				title: "We Don't Need to Talk About It",
				trackNumber: 8,
			},
			{ durationSeconds: 158, id: 'track-221', title: 'Hey Man', trackNumber: 9 },
			{ durationSeconds: 211, id: 'track-222', title: 'Comfort in the Clutter', trackNumber: 10 },
			{ durationSeconds: 327, id: 'track-45', title: 'Lean Into Life', trackNumber: 11 },
			{ durationSeconds: 126, id: 'track-223', title: 'Tell the Boys', trackNumber: 12 },
			{ durationSeconds: 202, id: 'track-224', title: 'Perfect Teeth', trackNumber: 13 },
		],
	},
	{
		albumArtist: 'Petey USA',
		artwork: 'https://lastfm.freetls.fastly.net/i/u/ar0/26abd405dd4e783afe5fb601ff3ff64f.jpg',
		bio: 'USA is Petey USA\'s second studio album, released in 2023. More expansive than his debut, the record explores the bittersweet texture of American life — family, distance, and growing up — with a warmth and detail that elevated him from TikTok curiosity to genuinely acclaimed songwriter. "Family of Six" is among the album\'s most affecting moments.',
		id: 'album-24',
		releaseYear: 2023,
		title: 'USA',
		tracks: [
			{ durationSeconds: 94, id: 'track-155', title: 'Bags Theme', trackNumber: 1 },
			{ durationSeconds: 172, id: 'track-333', title: "I'll Wait", trackNumber: 2 },
			{
				durationSeconds: 233,
				id: 'track-156',
				title: 'I Tried to Draw a Straight Line',
				trackNumber: 3,
			},
			{ durationSeconds: 182, id: 'track-48', title: 'Home Alone House', trackNumber: 4 },
			{ durationSeconds: 214, id: 'track-334', title: 'Skip This One', trackNumber: 5 },
			{ durationSeconds: 197, id: 'track-157', title: "Did I Mention I'm Sorry", trackNumber: 6 },
			{ durationSeconds: 144, id: 'track-335', title: 'Birds of a Feather', trackNumber: 7 },
			{ durationSeconds: 214, id: 'track-336', title: 'Living Like This', trackNumber: 8 },
			{ durationSeconds: 300, id: 'track-47', title: 'Family of Six', trackNumber: 9 },
			{ durationSeconds: 243, id: 'track-337', title: 'The Freedom to Fuck Off', trackNumber: 10 },
			{ durationSeconds: 273, id: 'track-338', title: 'How Bout That', trackNumber: 11 },
			{ durationSeconds: 305, id: 'track-339', title: 'Goodnight Nurse', trackNumber: 12 },
		],
	},
	{
		albumArtist: 'Jane Remover',
		artwork: 'https://coverartarchive.org/release/f765dd4e-6d1b-466d-901e-ba9827391796/front-500',
		bio: 'Frailty is Jane Remover\'s debut album, released November 2021 via deadAir records. Inspired by producers like Porter Robinson and Skrillex, the album incorporates samples from Pokémon and Undertale, with the artist stating she was "finally making the music I wanted to make since I was 9." It received critical acclaim, earning spots on year-end lists from both Pitchfork and Anthony Fantano, and established Jane Remover as a leading voice in hyperpop and PC music-adjacent scenes.',
		id: 'album-25',
		releaseYear: 2021,
		title: 'Frailty',
		tracks: [
			{ durationSeconds: 181, id: 'track-159', title: 'Goldfish', trackNumber: 1 },
			{ durationSeconds: 255, id: 'track-160', title: 'Your Clothes', trackNumber: 2 },
			{ durationSeconds: 234, id: 'track-164', title: 'Misplace', trackNumber: 3 },
			{ durationSeconds: 221, id: 'track-161', title: 'Pretender', trackNumber: 4 },
			{ durationSeconds: 298, id: 'track-49', title: 'Search Party', trackNumber: 5 },
			{ durationSeconds: 151, id: 'track-162', title: 'Buzzcut, Daisy', trackNumber: 6 },
			{ durationSeconds: 346, id: 'track-50', title: 'Movies For Guys', trackNumber: 7 },
			{ durationSeconds: 367, id: 'track-163', title: 'Kodak Moment', trackNumber: 8 },
			{ durationSeconds: 209, id: 'track-165', title: 'Can You Tell?', trackNumber: 9 },
			{ durationSeconds: 225, id: 'track-340', title: 'How To Lie', trackNumber: 10 },
			{ durationSeconds: 377, id: 'track-341', title: 'Champ', trackNumber: 11 },
			{
				durationSeconds: 234,
				id: 'track-342',
				title: "Eyes Off the Wheel, I'm a Star",
				trackNumber: 12,
			},
			{ durationSeconds: 333, id: 'track-343', title: "Let's Go Home", trackNumber: 13 },
		],
	},
	{
		albumArtist: 'Jane Remover',
		artwork: 'https://coverartarchive.org/release/b91d5017-c197-46e6-82b8-3663ea3fae59/front-500',
		bio: "Census Designated is Jane Remover's second album, released October 20, 2023 via deadAir records. The 10-track project emerged from ideas conceived shortly after Frailty, with 18 months spent refining the sound, inspired partly by a harrowing cross-country drive through blizzard conditions and a restorative stop in John Day, Oregon. Recorded across Studio North in Philadelphia and home studios, it balances confessional vulnerability with open-ended questioning about identity and place.",
		id: 'album-26',
		releaseYear: 2023,
		title: 'Census Designated',
		tracks: [
			{ durationSeconds: 344, id: 'track-166', title: 'Cage Girl / Camgirl', trackNumber: 1 },
			{ durationSeconds: 311, id: 'track-51', title: 'Lips', trackNumber: 2 },
			{ durationSeconds: 294, id: 'track-168', title: 'Fling', trackNumber: 3 },
			{ durationSeconds: 276, id: 'track-170', title: 'Holding a Leech', trackNumber: 4 },
			{ durationSeconds: 361, id: 'track-171', title: 'Backseat Girl', trackNumber: 5 },
			{ durationSeconds: 443, id: 'track-167', title: 'Idling Somewhere', trackNumber: 6 },
			{ durationSeconds: 391, id: 'track-344', title: 'Always Have Always Will', trackNumber: 7 },
			{ durationSeconds: 361, id: 'track-169', title: 'Census Designated', trackNumber: 8 },
			{ durationSeconds: 523, id: 'track-52', title: 'Video', trackNumber: 9 },
			{
				durationSeconds: 387,
				id: 'track-345',
				title: 'Contingency Song (Album Version)',
				trackNumber: 10,
			},
		],
	},
	{
		albumArtist: 'Liturgy',
		artwork: 'https://coverartarchive.org/release/4177877e-0adf-4a2e-921b-caf7198130f5/front-500',
		bio: "93696 is Liturgy's fifth studio album, released March 24, 2023. Named after a zip code in the Mojave Desert, the double-album-length record is their most ambitious and maximalist work to date — blending black metal, classical composition, opera, and electronic music across sprawling, multi-movement pieces. Haela Hunt-Hendrix wrote an accompanying philosophical treatise, extending the band's tradition of framing their music within a larger theoretical project.",
		id: 'album-27',
		releaseYear: 2023,
		title: '93696',
		tracks: [
			{ durationSeconds: 451, id: 'track-53', title: '93696', trackNumber: 1 },
			{ durationSeconds: 349, id: 'track-54', title: 'Angel of Sovereignty', trackNumber: 2 },
		],
	},
	{
		albumArtist: 'Liturgy',
		artwork: 'https://coverartarchive.org/release/345ad36c-adb4-404e-95fc-ccffcfba10e0/front-500',
		bio: "Origin of the Alimonies is Liturgy's fourth studio album, released September 25, 2020. The record is a suite of four extended pieces blending orchestral arrangements, synthesizers, and black metal, centred on themes of loss, transformation, and rebirth. It is one of Haela Hunt-Hendrix's most personal works, written during a period of significant change in her life.",
		id: 'album-28',
		releaseYear: 2020,
		title: 'Origin of the Alimonies',
		tracks: [
			{ durationSeconds: 315, id: 'track-55', title: 'Murmur of Chalices', trackNumber: 1 },
			{ durationSeconds: 328, id: 'track-172', title: 'Acqua', trackNumber: 2 },
			{ durationSeconds: 341, id: 'track-173', title: 'Orrery', trackNumber: 3 },
			{ durationSeconds: 372, id: 'track-56', title: 'Angel of Hierarchy', trackNumber: 4 },
		],
	},
	{
		albumArtist: 'Beecher',
		artwork: 'https://coverartarchive.org/release/109a6c4d-cfb0-41d5-983f-23b59bf5b5c4/front-500',
		bio: "Breaking the Fourth Wall is Beecher's debut album, released in 2001 on Earache Records. The Manchester band's ferocious blend of metalcore and hardcore made an immediate impact on the UK heavy scene. Its eleven tracks are relentless and technically demanding, establishing Beecher as one of Britain's most formidable acts of the early 2000s.",
		id: 'album-29',
		releaseYear: 2001,
		title: 'Breaking the Fourth Wall',
		tracks: [
			{ durationSeconds: 173, id: 'track-57', title: 'Let Them Drown', trackNumber: 1 },
			{ durationSeconds: 229, id: 'track-174', title: 'Dead for Weeks', trackNumber: 2 },
			{ durationSeconds: 234, id: 'track-175', title: 'Burning Surface', trackNumber: 3 },
			{ durationSeconds: 143, id: 'track-176', title: 'Arrow Flies', trackNumber: 4 },
			{ durationSeconds: 81, id: 'track-177', title: 'Mercury Switch', trackNumber: 5 },
			{ durationSeconds: 123, id: 'track-178', title: 'Floating Point', trackNumber: 6 },
			{ durationSeconds: 238, id: 'track-58', title: 'The Only One I Know', trackNumber: 7 },
			{ durationSeconds: 205, id: 'track-225', title: 'Red Diesel', trackNumber: 8 },
			{ durationSeconds: 143, id: 'track-226', title: 'Cabin Boy Jumped Ship', trackNumber: 9 },
			{ durationSeconds: 351, id: 'track-227', title: 'An Important Letter', trackNumber: 10 },
			{
				durationSeconds: 866,
				id: 'track-228',
				title: 'Ladder Theory / Crack Fiend',
				trackNumber: 11,
			},
		],
	},
	{
		albumArtist: 'Beecher',
		artwork: 'https://coverartarchive.org/release/3bf0feb5-6d6b-4eff-872d-4ac771210b9e/front-500',
		bio: "This Elegy, His Autopsy is Beecher's second and final studio album, released in 2003 on Earache Records. More refined and brutal than their debut, the record showcases the band at their technical peak — tight, angular riffs colliding with ferocious rhythm work and Edward Godby's corrosive vocals. The band disbanded in 2006, making this their definitive statement.",
		id: 'album-30',
		releaseYear: 2003,
		title: 'This Elegy, His Autopsy',
		tracks: [
			{
				durationSeconds: 156,
				id: 'track-179',
				title: "It's Good Weather for Black Leather",
				trackNumber: 1,
			},
			{ durationSeconds: 124, id: 'track-59', title: 'Function! Function!', trackNumber: 2 },
			{
				durationSeconds: 64,
				id: 'track-180',
				title: 'The Womaniser & the Alcoholic',
				trackNumber: 3,
			},
			{ durationSeconds: 103, id: 'track-181', title: 'Knight the Arsonist', trackNumber: 4 },
			{ durationSeconds: 246, id: 'track-182', title: 'Not Guilty', trackNumber: 5 },
			{
				durationSeconds: 242,
				id: 'track-183',
				title: 'And on the Day That He Became a Human Plumb-Line',
				trackNumber: 6,
			},
			{
				durationSeconds: 256,
				id: 'track-184',
				title: 'Psycho Galvanic Skin Response',
				trackNumber: 7,
			},
			{ durationSeconds: 161, id: 'track-60', title: 'Man the Traps', trackNumber: 8 },
			{ durationSeconds: 134, id: 'track-229', title: 'Brown Eyes (No Name)', trackNumber: 9 },
			{ durationSeconds: 82, id: 'track-230', title: 'The Biting Cold', trackNumber: 10 },
			{
				durationSeconds: 247,
				id: 'track-231',
				title: "I Won't Miss or Be Missed",
				trackNumber: 11,
			},
			{ durationSeconds: 152, id: 'track-232', title: 'Happiness', trackNumber: 12 },
			{ durationSeconds: 505, id: 'track-233', title: 'Reach Up to the Gods', trackNumber: 13 },
		],
	},
	{
		albumArtist: 'Charli XCX',
		artwork: 'https://lastfm.freetls.fastly.net/i/u/ar0/b00527c6ae0cd1d4c9bf3706b130ad56.jpg',
		bio: 'Brat is Charli xcx\'s sixth studio album, released June 7, 2024, drawing inspiration from London\'s underground rave scene and blending EDM, hyperpop, and dance elements with minimalist production. The album balances aggression with vulnerable, introspective lyrics exploring contentious relationships and personal grief, and spawned the cultural phenomenon of "brat summer." It won Best Dance/Electronic Album at the 67th Grammy Awards.',
		id: 'album-31',
		releaseYear: 2024,
		title: 'Brat',
		tracks: [
			{ durationSeconds: 131, id: 'track-61', title: '360', trackNumber: 1 },
			{ durationSeconds: 145, id: 'track-62', title: 'Von dutch', trackNumber: 2 },
		],
	},
	{
		albumArtist: 'Charli XCX',
		artwork: 'https://coverartarchive.org/release/2c951df6-cbe4-4239-9a43-e54e8a50a468/front-500',
		bio: 'Crash is Charli xcx\'s fifth studio album, released March 2022, featuring 80s, 90s, and 00s-inspired synth-pop and dance-pop production. Promoted through singles including "Good Ones," "New Shapes," and "Beg for You," Charli adopted an "evil era" persona during the rollout. The album\'s aesthetic drew inspiration from David Cronenberg\'s 1996 film, incorporating themes of femme fatale power and car crash imagery throughout.',
		id: 'album-32',
		releaseYear: 2022,
		title: 'Crash',
		tracks: [
			{ durationSeconds: 151, id: 'track-63', title: 'Crash', trackNumber: 1 },
			{ durationSeconds: 201, id: 'track-300', title: 'New Shapes', trackNumber: 2 },
			{ durationSeconds: 137, id: 'track-64', title: 'Good Ones', trackNumber: 3 },
			{ durationSeconds: 189, id: 'track-301', title: 'Constant Repeat', trackNumber: 4 },
			{ durationSeconds: 168, id: 'track-302', title: 'Beg for You', trackNumber: 5 },
			{ durationSeconds: 147, id: 'track-303', title: 'Move Me', trackNumber: 6 },
			{ durationSeconds: 160, id: 'track-304', title: 'Baby', trackNumber: 7 },
			{ durationSeconds: 237, id: 'track-305', title: 'Lightning', trackNumber: 8 },
			{ durationSeconds: 183, id: 'track-306', title: 'Every Rule', trackNumber: 9 },
			{ durationSeconds: 139, id: 'track-307', title: 'Yuck', trackNumber: 10 },
			{ durationSeconds: 146, id: 'track-308', title: 'Used to Know Me', trackNumber: 11 },
			{ durationSeconds: 195, id: 'track-309', title: 'Twice', trackNumber: 12 },
			{ durationSeconds: 194, id: 'track-310', title: 'Selfish Girl', trackNumber: 13 },
			{
				durationSeconds: 157,
				id: 'track-311',
				title: 'How Can I Not Know What I Need Right Now',
				trackNumber: 14,
			},
			{ durationSeconds: 161, id: 'track-312', title: 'Sorry If I Hurt You', trackNumber: 15 },
			{ durationSeconds: 184, id: 'track-313', title: 'What You Think About Me', trackNumber: 16 },
		],
	},
	{
		albumArtist: 'Chelsea Wolfe',
		artwork: 'https://coverartarchive.org/release/2a8eaa8c-beea-43d4-b8bf-671812291546/front-500',
		bio: "Hiss Spun is Chelsea Wolfe's sixth album, recorded in Salem, Massachusetts during winter 2017, exploring themes of personal upheaval and global chaos. The record combines groaning bass, pounding drums, and distorted textures with sound collages sourced from construction sites, wildlife, and industrial spaces. Wolfe describes the album as both escapist and deeply personal, examining cycles of mood, obsession, and self-examination.",
		id: 'album-33',
		releaseYear: 2017,
		title: 'Hiss Spun',
		tracks: [
			{ durationSeconds: 329, id: 'track-65', title: 'Spun', trackNumber: 1 },
			{ durationSeconds: 259, id: 'track-66', title: '16 Psyche', trackNumber: 2 },
			{ durationSeconds: 183, id: 'track-185', title: 'Vex', trackNumber: 3 },
			{ durationSeconds: 74, id: 'track-314', title: 'Strain', trackNumber: 4 },
			{ durationSeconds: 362, id: 'track-315', title: 'The Culling', trackNumber: 5 },
			{ durationSeconds: 293, id: 'track-316', title: 'Particle Flux', trackNumber: 6 },
			{ durationSeconds: 368, id: 'track-317', title: 'Twin Fawn', trackNumber: 7 },
			{ durationSeconds: 171, id: 'track-318', title: 'Offering', trackNumber: 8 },
			{ durationSeconds: 262, id: 'track-319', title: 'Static Hum', trackNumber: 9 },
			{ durationSeconds: 115, id: 'track-320', title: 'Welt', trackNumber: 10 },
			{ durationSeconds: 305, id: 'track-321', title: 'Two Spirit', trackNumber: 11 },
			{ durationSeconds: 184, id: 'track-322', title: 'Scrape', trackNumber: 12 },
		],
	},
	{
		albumArtist: 'Chelsea Wolfe',
		artwork: 'https://coverartarchive.org/release/33922aab-40f8-4d43-8d1c-7693562f784e/front-500',
		bio: "She Reaches Out to She Reaches Out to She is Chelsea Wolfe's seventh studio album, released February 23, 2024. Written during her sobriety journey that began in 2021, the record explores themes of severing unhealthy connections, personal rebirth, and the non-linear nature of healing. It marks a shift toward trip-hop and industrial textures, with the circular title itself reflecting the cyclical process of transformation it documents.",
		id: 'album-34',
		releaseYear: 2024,
		title: 'She Reaches Out to She Reaches Out to She',
		tracks: [
			{
				durationSeconds: 241,
				id: 'track-67',
				title: 'Whispers in the Echo Chamber',
				trackNumber: 1,
			},
			{ durationSeconds: 263, id: 'track-186', title: 'House of Self-Undoing', trackNumber: 2 },
			{ durationSeconds: 266, id: 'track-187', title: 'Everything Turns Blue', trackNumber: 3 },
			{ durationSeconds: 248, id: 'track-68', title: 'Tunnel Lights', trackNumber: 4 },
			{ durationSeconds: 292, id: 'track-323', title: 'The Liminal', trackNumber: 5 },
			{ durationSeconds: 274, id: 'track-324', title: 'Eyes Like Nightshade', trackNumber: 6 },
			{ durationSeconds: 264, id: 'track-325', title: 'Salt', trackNumber: 7 },
			{ durationSeconds: 207, id: 'track-189', title: 'Unseen World', trackNumber: 8 },
			{ durationSeconds: 250, id: 'track-326', title: 'Place in the Sun', trackNumber: 9 },
			{ durationSeconds: 274, id: 'track-188', title: 'Dusk', trackNumber: 10 },
		],
	},
];
