import type { Artist } from '../models/Artist';

export const mockArtists: Array<Artist> = [
	{
		bio: 'Converge is an American hardcore punk band from Salem, Massachusetts, formed in 1990. Comprising vocalist Jacob Bannon, guitarist Kurt Ballou, bassist Nate Newton, and drummer Ben Koller, the band is known for their ferocious live performances and dense, layered recordings. Their 2001 album Jane Doe is widely regarded as a landmark in metalcore and post-hardcore. Over three decades they have released critically acclaimed records and maintained absolute creative and label independence through their own Deathwish Inc. imprint.',
		id: 'artist-1',
		imageUrl: 'https://lastfm.freetls.fastly.net/i/u/ar0/8e48ec533261e56cb1e01394336fe926.jpg',
		logoUrl: '',
		name: 'Converge',
	},
	{
		bio: 'Agriculture is a black metal band from Los Angeles, California. Formed around the vision of guitarist/vocalist Dan Schmoyer, the project blends cascading tremolo riffs with pastoral, almost devotional atmospheres. Their 2023 self-titled debut received widespread acclaim for dissolving the boundary between transcendence and brutality. The Spiritual Sound (2025) deepened their spiritual exploration, drawing on Eastern philosophy alongside the intensity of the black metal tradition.',
		id: 'artist-2',
		imageUrl: 'https://lastfm.freetls.fastly.net/i/u/ar0/7b78e4e1f85edca94d5aac03e0824b83.jpg',
		logoUrl: '',
		name: 'Agriculture',
	},
	{
		bio: "Chat Pile is a noise rock band from Oklahoma City, Oklahoma. Formed in 2019, the quartet — Raygun Busch (vocals), Luther Manhole (guitar), Stin (bass), and Cap'n Ron (drums) — traffic in bleak, grinding riffs and unflinching examinations of American decay. God's Country (2022) announced them as one of the most singular voices in heavy music, its lyrics channelling poverty, violence, and spiritual exhaustion with visceral clarity.",
		id: 'artist-3',
		imageUrl: 'https://lastfm.freetls.fastly.net/i/u/ar0/7ac36a80b94625f56c3da62c45079f54.jpg',
		logoUrl: '',
		name: 'Chat Pile',
	},
	{
		bio: 'HEALTH is an American industrial/noise rock band from Los Angeles comprising drummer B.J. Miller, vocalist Jake Duzsik, and bassist John Famiglietti. They gained initial prominence through a Crystal Castles remix of their track "Crimewave" before releasing their self-titled debut in 2007, and have since released six studio albums including RAT WARS (2023). Beyond their core discography, HEALTH has contributed significantly to video game soundtracks for titles like Max Payne 3, Grand Theft Auto V, and Cyberpunk 2077, while collaborating with artists including Nine Inch Nails and Poppy on their DISCO4 series.',
		id: 'artist-4',
		imageUrl: 'https://lastfm.freetls.fastly.net/i/u/ar0/119078c6a04343d1692f2357e207ac68.jpg',
		logoUrl: '',
		name: 'HEALTH',
	},
	{
		bio: 'Single Mothers is a hardcore band from London, Ontario, Canada, formed in 2009. The group is known for delivering frantic, frenzied, and outrageous live performances featuring sing-alongs, crowd surfing, and mosh pits. Their sound blends punk, indie, and post-hardcore elements with fast rhythms, melodic lead guitar, and harsh, anthematic vocals exploring themes like failed relationships and financial struggle.',
		id: 'artist-5',
		imageUrl: 'https://lastfm.freetls.fastly.net/i/u/ar0/8a390537a8b1cedc4e0b41736822ddbb.jpg',
		logoUrl: '',
		name: 'Single Mothers',
	},
	{
		bio: 'Touché Amoré is a post-hardcore band from Burbank, California, formed in 2007, consisting of Jeremy Bolm on vocals, guitarists Clayton Stevens and Nick Steinhardt, Tyler Kirby on bass, and drummer Elliot Babin. They have released five studio albums, including Stage Four (2016) and Lament (2020) through Epitaph Records. The band is recognized for their confessional lyrics and fusion of influences from bands like Converge and Pg.99, and are considered part of the screamo revival and post-hardcore movement.',
		id: 'artist-6',
		imageUrl: 'https://lastfm.freetls.fastly.net/i/u/ar0/a020624728f84e2ead51c65ef2e64fdc.jpg',
		logoUrl: '',
		name: 'Touche Amore',
	},
	{
		bio: 'The Armed is a hardcore punk and extreme metal band from Detroit, Michigan, formed in 2009. Known for complex guitar work, polyrhythmic drumming, and synthesized elements, the band deliberately obscures their lineup and presents an ever-shifting collective identity. Their records, mixed by Kurt Ballou of Converge, push the formal limits of hardcore into maximalist pop territory — most fully realised on ULTRAPOP (2021) and Perfect Saviors (2023).',
		id: 'artist-7',
		imageUrl: 'https://lastfm.freetls.fastly.net/i/u/ar0/2e4c431fc08459b53f740e4c17667fd0.jpg',
		logoUrl: '',
		name: 'The Armed',
	},
	{
		bio: "Birds in Row is a post-hardcore and screamo band from Laval, France, formed in 2009. The three-piece intentionally obscures member identities in promotional materials, referring to themselves only by single letters to emphasize the band as a unified entity rather than individuals. They have released three full-length albums — You, Me & the Violence (2012), We Already Lost the World (2018), and Gris Klein (2022) — the latter on Cult of Luna's Red Creek label.",
		id: 'artist-8',
		imageUrl: 'https://lastfm.freetls.fastly.net/i/u/ar0/b87a10c4701e6d4b8121cefcafed3afc.jpg',
		logoUrl: '',
		name: 'Birds In Row',
	},
	{
		bio: 'Carly Rae Jepsen is a Canadian singer-songwriter born November 21, 1985, in Mission, British Columbia. She achieved breakthrough success in 2012 with "Call Me Maybe," which became the best-selling single of that year. Her discography spans folk, dance-pop, and synth-pop genres, and she is widely celebrated for Emotion (2015), an album that gained a devoted cult following for its sophisticated approach to heartbreak and longing.',
		id: 'artist-9',
		imageUrl: 'https://lastfm.freetls.fastly.net/i/u/ar0/975a5d9bf4fe44e46c8c6f3a2eb6cd95.jpg',
		logoUrl: '',
		name: 'Carly Rae Jepsen',
	},
	{
		bio: "Venturing is the alternative rock side project of American singer, songwriter, and producer Jane Remover. Originally framed with fictional 1990s band lore set in South Dakota, that backstory was retired with the release of the debut album Ghostholding (2023). The project channels a more guitar-driven, shoegaze-adjacent sound compared to Jane Remover's solo electronic work.",
		id: 'artist-10',
		imageUrl: 'https://lastfm.freetls.fastly.net/i/u/ar0/2c4a0ba723c57e3899df18fbdd6af27f.jpg',
		logoUrl: '',
		name: 'Venturing',
	},
	{
		bio: 'Peter Martin, professionally known as Petey USA, is an American musician born November 17, 1991, in Royal Oak, Michigan. He gained prominence on TikTok during the COVID-19 pandemic and is known for his confessional, witty indie pop songwriting. His albums Lean Into Life (2021) and USA (2023) established him as a distinct voice in the DIY singer-songwriter scene.',
		id: 'artist-11',
		imageUrl: 'https://lastfm.freetls.fastly.net/i/u/ar0/f56f59829a545b75b376829108ef48e4.jpg',
		logoUrl: '',
		name: 'Petey USA',
	},
	{
		bio: 'Jane Remover is an American singer, songwriter, and producer from Newark, New Jersey, currently based in Chicago, who creates electronic-infused pop, hip-hop, and rock music. They pioneered the "dariacore" genre through their side project leroy, and gained recognition with their debut album Frailty (2021), which Pitchfork ranked among the year\'s best. After transitioning in 2022 and releasing their second album Census Designated in 2023, Jane continues developing a distinctive production style blending sampled EDM with contemporary alternative sounds.',
		id: 'artist-12',
		imageUrl: 'https://lastfm.freetls.fastly.net/i/u/ar0/db102101a989c4272a0179b1f1c3dcd8.jpg',
		logoUrl: '',
		name: 'Jane Remover',
	},
	{
		bio: 'Liturgy is an avant-garde black metal band from Brooklyn, New York, originally founded as the solo project of Haela Ravenna Hunt-Hendrix. The group expanded to a four-piece lineup in 2008 and describes their musical style as "transcendental black metal." They have released five studio albums, including Renihilation (2009), Aesthethica (2011), The Ark Work (2015), H.A.Q.Q. (2019), and Origin of the Alimonies (2020), each pushing further into orchestral and conceptual territory.',
		id: 'artist-13',
		imageUrl: 'https://lastfm.freetls.fastly.net/i/u/ar0/761456a2985ec9ff2ffc972376edc53b.jpg',
		logoUrl: '',
		name: 'Liturgy',
	},
	{
		bio: 'Beecher was a Manchester-based metal and hardcore punk band active from 2001 to 2006. The group featured guitarists Daniel Plant and Mark Lyons alongside vocalist Edward Godby, bassist David Hopkinson, and drummer Will Shaw, releasing albums including Breaking the Fourth Wall (2001) and This Elegy, His Autopsy (2003) on Earache Records. After disbanding in 2006, members went on to form the project The Freezing Fog.',
		id: 'artist-14',
		imageUrl: 'https://lastfm.freetls.fastly.net/i/u/ar0/bdd09d421b244c22b36146ec6d69900d.jpg',
		logoUrl: '',
		name: 'Beecher',
	},
	{
		bio: 'Charlotte Emma Aitchison, known professionally as Charli xcx, is a British pop singer and songwriter born August 2, 1992, in Cambridge, England. She rose to prominence after being featured on Icona Pop\'s 2012 hit "I Love It" and achieved major commercial success with collaborations like Iggy Azalea\'s "Fancy" (2014). Known for her experimental approach to pop music, particularly through work with UK collective PC Music, she has released six studio albums including the critically acclaimed Brat (2024), which won three Grammy Awards.',
		id: 'artist-15',
		imageUrl: 'https://lastfm.freetls.fastly.net/i/u/ar0/98b15d563e70d467c883942cf31dc842.jpg',
		logoUrl: '',
		name: 'Charli XCX',
	},
	{
		bio: 'Chelsea Wolfe is an American singer-songwriter born November 14, 1983, in Roseville, California, whose work blends gothic rock, doom metal, folk, and darkwave into a distinctive sound. Growing up with a musician father, she began writing poetry at age 7 and recording songs by age 9, developing a style influenced by filmmakers like David Lynch and Soviet apocalyptic literature. Her discography spans heavier albums like Abyss (2015) and Hiss Spun (2017) to more recent explorations of trip-hop and industrial on She Reaches Out to She Reaches Out to She (2024), inspired by her sobriety journey beginning in 2021.',
		id: 'artist-16',
		imageUrl: 'https://lastfm.freetls.fastly.net/i/u/ar0/e4453ad67beb5451a4729befe09e3f8a.jpg',
		logoUrl: '',
		name: 'Chelsea Wolfe',
	},
];
