#:schema https://raw.githubusercontent.com/tx3stn/vrsn/refs/heads/main/.schema/vrsn.json
verbose = false
files = ['package.json', 'MODULE.bazel', 'atolla/src/version.ts']

[bump]
commit = true
commit-msg = 'chore: bump version to {{.Version}}'
git-tag = false
tag-msg = 'release {{.Version}}'

[check]
base-branch = 'main'
