import { DEFAULT_PLAYER_GROUP, type Player, PlayerStates, PlayerTiers } from '../models/Player';

export const MOCK_PLAYERS: Array<Player> = [
	{
		address: '192.168.1.42',
		enabled: true,
		group: DEFAULT_PLAYER_GROUP,
		icon: null,
		id: '4f3c9a1de8b27065',
		isThisDevice: false,
		lastError: null,
		name: 'Kitchen',
		reachable: true,
		ready: true,
		state: PlayerStates.playing,
		tier: PlayerTiers.tight,
	},
	{
		address: '192.168.1.43',
		enabled: true,
		group: DEFAULT_PLAYER_GROUP,
		icon: null,
		id: '91b04e7c2a6df358',
		isThisDevice: false,
		lastError: null,
		name: 'Living Room',
		reachable: true,
		ready: true,
		state: PlayerStates.playing,
		tier: PlayerTiers.tight,
	},
	{
		address: '192.168.1.44',
		enabled: false,
		group: DEFAULT_PLAYER_GROUP,
		icon: null,
		id: 'c7e21f8a05b9d346',
		isThisDevice: false,
		lastError: null,
		name: 'Office',
		reachable: true,
		ready: true,
		state: PlayerStates.idle,
		tier: PlayerTiers.tight,
	},
	{
		address: '192.168.1.45',
		enabled: true,
		group: DEFAULT_PLAYER_GROUP,
		icon: null,
		id: '2d8a6b3f14c07e9b',
		isThisDevice: false,
		lastError: null,
		name: 'Bathroom',
		reachable: true,
		ready: false,
		state: PlayerStates.idle,
		tier: PlayerTiers.tight,
	},
	{
		address: '192.168.1.46',
		enabled: true,
		group: DEFAULT_PLAYER_GROUP,
		icon: null,
		id: 'a05f7c93e2b1d648',
		isThisDevice: false,
		lastError: 'could not reach the media server',
		name: 'Garage',
		reachable: true,
		ready: false,
		state: PlayerStates.idle,
		tier: PlayerTiers.tight,
	},
	{
		address: '192.168.1.47',
		enabled: false,
		group: DEFAULT_PLAYER_GROUP,
		icon: null,
		id: '6e13b8d0f7a25c94',
		isThisDevice: false,
		lastError: null,
		name: 'Shed',
		reachable: false,
		ready: false,
		state: PlayerStates.idle,
		tier: PlayerTiers.tight,
	},
	{
		address: null,
		enabled: false,
		group: DEFAULT_PLAYER_GROUP,
		icon: null,
		id: 'this-device',
		isThisDevice: true,
		lastError: null,
		name: 'This phone',
		reachable: true,
		ready: true,
		state: PlayerStates.idle,
		tier: PlayerTiers.loose,
	},
];
