load("@valdi//bzl/valdi:valdi_cli_application.bzl", "valdi_cli_application")
load("@valdi//bzl/valdi:valdi_module.bzl", "valdi_module")

package(default_visibility = ["//visibility:public"])

valdi_module(
    name = "atolla_headless",
    srcs = glob(
        [
            "src/**/*.ts",
            "src/**/*.d.ts",
            "strings/**/*.json",
        ],
        exclude = ["src/**/*.test.ts"],
    ),
    exclude_patterns = [".*\\.test\\.ts$"],
    strings_dir = "strings",
    visibility = ["//visibility:public"],
    deps = [
        "//atolla_core",
        "@valdi//src/valdi_modules/src/valdi/valdi_core",
    ],
)

valdi_cli_application(
    name = "atolla_headless_cli",
    script_path = "atolla_headless/src/main",
    deps = [":atolla_headless"],
)
