/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/hello": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Identity and the API versions this player speaks.
         * @description Unauthenticated, and the one route that answers whatever version it is asked for: refusing
         *     discovery on a version mismatch would leave a mixed-version fleet unable to find out why.
         *
         *     The body is built once at startup and served verbatim by the server, so it keeps answering
         *     while the JS thread is busy. Every field is a process-lifetime constant; anything that
         *     changes lives in the beacon or `/state`. Takes no body.
         */
        get: operations["getHello"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pair": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Trade the player's pairing code for a controller token.
         * @description The code is compared by the server, so a wrong one never reaches TypeScript. Whitespace is
         *     stripped before the comparison, which is what lets a controller submit the spaced form the
         *     player displays. A daemon with no code provisioned refuses every attempt.
         *
         *     The body may carry a media server for the player to use. That is a Jellyfin token the
         *     controller mints for this player, not the user's own session token, so a compromised
         *     speaker costs one revocable credential.
         *
         *     Bodies are capped at 4 KiB and must declare a `Content-Length`.
         *
         *     Failed attempts are throttled per caller address. Three refusals earn a `429` carrying
         *     `Retry-After: 1`. A throttled attempt records nothing, so hammering does not extend the
         *     block: wait it out and the next wrong code is a `401` again, with the one after it held for
         *     2 seconds, then 4. A successful pair clears the failures behind it.
         */
        post: operations["pair"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/command": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Act on the player's queue or playback.
         * @description Thirteen commands share one route, discriminated on `command`. The name and the shape of
         *     its members are the wire contract, so `command.zig` refuses an unknown name or a malformed
         *     member before the request crosses the bridge. The `tracks` array is the exception and
         *     passes through as opaque bytes: `Track` is a TypeScript interface with one source of truth,
         *     so a second definition in Zig would start refusing valid queues the day a field was added,
         *     and TypeScript needs the parsed object regardless.
         *
         *     A `202` says the command was accepted, not that it has happened. The leader applies it to
         *     the queue it owns and answers with the state version that reflects it. What the speakers
         *     then do is visible only through `GET /state`: a member can miss the readiness barrier, and
         *     a `previous` can restart the current track instead of stepping back. A controller that
         *     reads this response as the outcome will show something the players are not doing.
         *
         *     Commands naming a queue position may also carry the `trackId` expected there. A controller
         *     acts on a mirror that can be a long poll behind, and with several controllers paired the
         *     queue moves under it, so an index on its own can point at a track the user never chose.
         *     When the id does not match, the player drops the command.
         *
         *     `setVolume` and `setMembers` appear in the design but are not accepted yet: both are group
         *     state rather than queue state and arrive with the group coordinator. Until then they are
         *     refused as `malformed_body`, like any other unknown name.
         *
         *     Bodies are capped at 1 MiB and must declare a `Content-Length`.
         */
        post: operations["sendCommand"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The player's queue, playback and group state.
         * @description Everything a controller mirrors, in one snapshot. A controller holds the last one it was
         *     given and replaces it wholesale; there are no partial updates, because a snapshot small
         *     enough to send whole is simpler than a diff both ends have to agree on.
         *
         *     The route is a long poll. Passing `since` asks for the first snapshot newer than that
         *     version, and the daemon holds the request open for up to 25 seconds waiting for one, though
         *     a change wakes it immediately. Twenty-five seconds passing with nothing new is not an
         *     error: it answers `304` with no body, because the controller already holds that snapshot
         *     and re-sending a queue of several hundred tracks every 25 seconds would be the only thing
         *     the wire carried. Omitting `since` answers the current snapshot straight away, which is how
         *     a controller gets its first one.
         *
         *     The loop a controller runs is to read a snapshot, apply it, then ask again with the
         *     `version` it applied. A `304` means ask again unchanged, and a `200` means replace the
         *     mirror. Position is the one part that does not need a new snapshot, which is what
         *     `positionAtMs` is for.
         */
        get: operations["getState"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Format: int32
         * @description A version of this contract. There is one, and this is the single place that changes when a
         *     second one lands.
         * @example 1
         * @constant
         */
        ApiVersion: 1;
        /**
         * @description RFC 9457 problem details, served as `application/problem+json`. `type` is omitted rather
         *     than written as `about:blank`, which the RFC says is what an absent `type` means, so it
         *     stays free for a documentation URL later. Extension members are flat alongside the standard
         *     ones and are dropped when a given problem does not carry them.
         *
         *     `code` is the stable vocabulary a client switches on. `title` is prose and may be reworded.
         * @example {
         *       "code": "not_found",
         *       "status": 404,
         *       "title": "not found"
         *     }
         */
        Problem: {
            /**
             * @description The machine-readable name of this refusal, and the whole vocabulary the daemon can
             *     answer with. `internal` is what a handler that threw answers, and doubles as the
             *     fallback body when a problem will not fit its render buffer.
             * @example invalid_pairing_code
             * @enum {string}
             */
            code: "body_too_large" | "busy" | "expectation_failed" | "handler_timeout" | "headers_too_large" | "incomplete_body" | "internal" | "invalid_pairing_code" | "invalid_token" | "length_required" | "malformed_body" | "method_not_allowed" | "not_found" | "not_implemented" | "too_many_attempts" | "unavailable" | "unsupported_api_version";
            /**
             * @description Rarely sent. Naming the field that failed tells an unauthenticated caller which field
             *     to fix, and `/pair` is the one body a stranger on the LAN can post. Printable ASCII,
             *     and short: the whole rendered problem has to fit a 256-byte buffer or the daemon falls
             *     back to `internal`.
             * @example try later
             */
            detail?: string;
            /**
             * Format: int32
             * @description How long to wait before trying again, repeated in the `Retry-After` header. The
             *     throttle doubles from 1 second and the limiter caps it at 60.
             * @example 1
             */
            retryAfterSeconds?: number;
            /**
             * Format: int32
             * @description The HTTP status this body accompanies.
             * @example 400
             */
            status: number;
            /**
             * @description The API versions the daemon speaks. Sent with `unsupported_api_version`.
             * @example [
             *       1
             *     ]
             */
            supported?: components["schemas"]["ApiVersion"][];
            /**
             * @description A short human-readable summary of the refusal. Every one the daemon carries is
             *     lowercase words, and it is prose: switch on `code`, not on this.
             * @example not found
             */
            title: string;
        };
        /** @description A player's identity, constant for the life of the process. */
        Hello: {
            /**
             * @description Every version of this contract the daemon speaks.
             * @example [
             *       1
             *     ]
             */
            apiVersions: components["schemas"]["ApiVersion"][];
            /**
             * @description The player's stable identifier, minted once and kept in its data directory.
             * @example 4f3c9a1de8b27065
             */
            id: string;
            /**
             * @description The display name from the player's config, empty if none was set. The whole `/hello`
             *     body has to fit a 1 KiB buffer, so a very long name stops the route answering at all.
             * @example Kitchen
             */
            name: string;
            /**
             * @description How tightly this player can synchronise. A daemon is `tight`; a phone joining a group
             *     is `loose`.
             * @example tight
             * @enum {string}
             */
            tier: "loose" | "tight";
            /**
             * @description The current API version, duplicating `apiVersions`' last entry. Short because the
             *     beacon repeats it in every datagram, where there is no header to carry it.
             * @example 1
             */
            v: components["schemas"]["ApiVersion"];
            /**
             * @description The atolla build the daemon is running.
             * @example 0.0.0
             */
            version: string;
        };
        /** @description A media server credential for the player to use on its own behalf. */
        MediaServer: {
            /**
             * @description A token minted for this player, revocable without touching the user's login.
             * @example 3d9f0c1b7a5e4826
             */
            accessToken: string;
            /**
             * Format: uri
             * @description Where the media server answers.
             * @example http://jellyfin.local:8096
             */
            baseUrl: string;
            /**
             * @description The device the token was minted against.
             * @example atolla-kitchen
             */
            deviceId: string;
            /**
             * @description The media server account the token belongs to.
             * @example 8b1f2c3d4e5f6071
             */
            userId: string;
        } & {
            [key: string]: unknown;
        };
        /**
         * @description Every length cap here is enforced by `pair.zig` before the request crosses the bridge, and
         *     an unknown member is ignored so a v1 daemon does not refuse a body a later controller added
         *     a field to.
         */
        PairRequest: {
            /**
             * @description The player's pairing code. The daemon strips whitespace before comparing, so the
             *     spaced form the player displays is accepted too, and it enforces only a 32-byte cap
             *     here: a code of the wrong shape is a `401` rather than a `400`, so the caller learns
             *     nothing about it.
             * @example 19524002
             */
            code: string;
            /**
             * @description Stable per controller. Pairing again under an id the player already knows replaces that
             *     record, so the old token dies.
             * @example phone-1
             */
            controllerId: string;
            /**
             * @description Shown to the user when they review what is paired. May be empty, but must be present:
             *     a body omitting it is refused.
             * @example pixel 8
             */
            controllerName: string;
            mediaServer?: components["schemas"]["MediaServer"];
        } & {
            [key: string]: unknown;
        };
        /** @description The credential the controller sends on every later request. */
        PairAccepted: {
            /**
             * @description 256 bits of entropy, hex encoded. Nothing types this, so it shares no shape with the
             *     pairing code.
             * @example 7c1e5a9b3d8f204617ca0be9352d8f7461a0c3d95e28b7f4016cad3928bf5e7d
             */
            token: string;
        };
        /**
         * Format: int32
         * @description A monotonic counter the leader bumps whenever the state a controller mirrors changes. Its
         *     only job is to order changes. It does not count commands: one command can settle several
         *     fields, and some changes have no command behind them at all.
         *
         *     Nothing persists it, so it starts again at 1 when the daemon restarts. Persisting would
         *     mean a disk write on every bump, which is every command, to protect against something a
         *     rule handles for nothing: a `since` higher than the current version names something the
         *     daemon will never reach, so it is answered immediately with the current snapshot rather
         *     than held for 25 seconds. A controller that outlived a restart gets one snapshot it may
         *     already have held, adopts the version in it, and carries on. A `since` equal to the current
         *     version is the ordinary case and does block, which is what a poll is for. Versions are
         *     ordered within a run of the daemon, and comparing them across runs means nothing.
         *
         *     The 32-bit ceiling takes a bump a second for 68 years to reach, and it keeps the value
         *     exact in every JSON parser. An `int64` would not, for a client reading it as a JavaScript
         *     number.
         * @example 412
         */
        StateVersion: number;
        /**
         * Format: int32
         * @description A position in the queue, counted from zero. The server holds no queue of its own, so the
         *     bound is only a sanity check, and it sits well above what the 1 MiB body cap lets a
         *     `setQueue` deliver. Whether the index falls inside the queue the player currently has is
         *     settled after the request crosses the bridge.
         * @example 3
         */
        TrackIndex: number;
        /**
         * @description The queue a command carries. The server hands this array across the bridge without parsing
         *     it, so it enforces neither the member shape nor `maxItems`: the 1 MiB body cap is what
         *     refuses an oversized queue, and it is reached first anyway. What checks the shape is the
         *     handler on the other side, which refuses the body as `malformed_body` if a member is not a
         *     track.
         * @example [
         *       {
         *         "duration": 293.4,
         *         "id": "1a2b3c4d5e6f7081",
         *         "name": "Xtal"
         *       }
         *     ]
         */
        Tracks: components["schemas"]["Track"][];
        /** @description The commands that carry no members beyond their own name. */
        CommandBare: {
            /**
             * @description `play` and `pause` act on the current track, `next` and `previous` move between
             *     tracks, and `shuffle` reorders what has not played yet.
             *
             *     `previous` follows the button rather than the word: the leader restarts the current
             *     track when it is more than three seconds in, and steps back otherwise. That is what
             *     the same button already does when the phone is playing.
             *      (enum property replaced by openapi-typescript)
             * @enum {string}
             */
            command: "next" | "pause" | "play" | "previous" | "shuffle";
        } & {
            [key: string]: unknown;
        };
        /** @description Move within the current track. */
        CommandSeek: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            command: "seek";
            /**
             * Format: int64
             * @description Where to move to, measured from the start of the track. Milliseconds, matching
             *     `/state`'s `positionMs`, though the player's own clock works in seconds and rounds.
             *     The bound is a day, which no track reaches. Whether the position falls inside the
             *     track being played is settled after the request crosses the bridge.
             * @example 91234
             */
            positionMs: number;
        } & {
            [key: string]: unknown;
        };
        /** @description Play a track already in the queue. */
        CommandJumpToIndex: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            command: "jumpToIndex";
            trackId?: components["schemas"]["CommandTrackId"];
            trackIndex: components["schemas"]["TrackIndex"];
        } & {
            [key: string]: unknown;
        };
        /**
         * @description Replace the queue outright and start playing. This is the largest body the API takes, and
         *     the reason `/command`'s cap is 1 MiB rather than the 4 KiB the other routes get.
         */
        CommandSetQueue: {
            /**
             * @description The album the queue came from, when it came from one. A queue with no album behind it,
             *     such as a shuffle across an artist, omits it. The server passes it through unparsed, as
             *     it does `tracks`.
             *
             *     An album that arrives malformed is dropped rather than refusing the command, which is
             *     the one place this route is lenient: the tracks are what the user asked to hear, and
             *     the album is the context they are shown in. A malformed `tracks` refuses.
             */
            album?: components["schemas"]["Album"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            command: "setQueue";
            trackIndex?: components["schemas"]["TrackIndex"];
            tracks: components["schemas"]["Tracks"];
        } & {
            [key: string]: unknown;
        };
        /** @description Append tracks to the end of the queue. */
        CommandAddToQueue: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            command: "addToQueue";
            tracks: components["schemas"]["Tracks"];
        } & {
            [key: string]: unknown;
        };
        /** @description Insert tracks directly after the current one, ahead of the rest of the queue. */
        CommandPlayNext: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            command: "playNext";
            tracks: components["schemas"]["Tracks"];
        } & {
            [key: string]: unknown;
        };
        /** @description Drop one track from the queue. */
        CommandRemoveAt: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            command: "removeAt";
            trackId?: components["schemas"]["CommandTrackId"];
            trackIndex: components["schemas"]["TrackIndex"];
        } & {
            [key: string]: unknown;
        };
        /** @description Reorder the queue by moving one track. */
        CommandMove: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            command: "move";
            fromIndex: components["schemas"]["TrackIndex"];
            toIndex: components["schemas"]["TrackIndex"];
            trackId?: components["schemas"]["CommandTrackId"];
        } & {
            [key: string]: unknown;
        };
        /**
         * @description Choose how the queue repeats. The controller sends the mode it wants rather than asking the
         *     player to cycle to the next one, because a mirror that is a long poll behind would cycle
         *     from a mode the player has already left. Naming the mode gives the same result whatever the
         *     player currently has.
         */
        CommandSetLoopMode: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            command: "setLoopMode";
            /**
             * @description `none` stops at the end of the queue, `queue` starts it again, `track` repeats the
             *     current one.
             * @example queue
             * @enum {string}
             */
            loopMode: "none" | "queue" | "track";
        } & {
            [key: string]: unknown;
        };
        /**
         * @description The track the controller expects to find at the position it named. Optional, and worth
         *     sending: the player drops the command when the id does not match, so a stale mirror cannot
         *     reorder or delete the wrong track. A command that omits it is applied to whatever sits at
         *     that position.
         * @example 3c4d5e6f708192a3
         */
        CommandTrackId: string;
        /**
         * @description One command for the player. `command` names it and the rest of the members belong to that
         *     name: an unknown name is `malformed_body`, as is a missing or wrongly typed member of a
         *     name the player does know.
         *
         *     A member belonging to no command is ignored rather than refused, as in `PairRequest`, so a
         *     v1 daemon keeps accepting a body that a later controller added a field to. That is why each
         *     variant is open rather than sealed.
         */
        Command: components["schemas"]["CommandBare"] | components["schemas"]["CommandSeek"] | components["schemas"]["CommandJumpToIndex"] | components["schemas"]["CommandSetQueue"] | components["schemas"]["CommandAddToQueue"] | components["schemas"]["CommandPlayNext"] | components["schemas"]["CommandRemoveAt"] | components["schemas"]["CommandMove"] | components["schemas"]["CommandSetLoopMode"];
        /**
         * @description The version the command produced. `GET /state?since=` with anything lower returns that
         *     snapshot without blocking, so a controller can read the result of its own command without
         *     waiting for the next change. It says nothing about what the speakers are doing.
         */
        CommandAccepted: {
            version: components["schemas"]["StateVersion"];
        };
        /**
         * @description A track, as much of one as a controller needs. `atolla_core/src/models/Track.ts` is the one
         *     source of truth and holds a good deal more: release dates, sort names, genres, disc and
         *     track numbers. The daemon relays all of it untouched, and this schema describes none of it,
         *     because nothing reading a snapshot depends on it. Listing those members here would make a
         *     second definition to keep in step with the first, and the spec is the copy that would be
         *     wrong once they drifted.
         *
         *     What is described is the members the interface requires, plus the ones a controller renders
         *     and navigates from. Anything else the media server supplied arrives alongside them.
         */
        Track: {
            /**
             * @description So a controller can offer to open the album this came from.
             * @example 6f2b8c4d1e9a3705
             */
            albumId?: string;
            /**
             * Format: uri
             * @description The artwork. A controller has no way to work this out, so it travels with the track.
             * @example http://jellyfin.local:8096/Items/6f2b8c4d/Images/Primary
             */
            albumImageUrl?: string;
            /** @example Selected Ambient Works */
            albumName?: string;
            /** @example 1c4e7a09 */
            artistId?: string;
            /** @example Aphex Twin */
            artistName?: string;
            /**
             * Format: double
             * @description Seconds, not milliseconds, because that is what the store and the audio engine work in.
             *     The playback position beside it is milliseconds: a position needs finer resolution than
             *     a length, and the asymmetry is deliberate.
             * @example 293.4
             */
            duration: number;
            /**
             * @description The media server's identifier. A command naming a queue position may carry it as a
             *     guard, and the native player matches the track it is playing by it.
             * @example 1a2b3c4d5e6f7081
             */
            id: string;
            /** @example Xtal */
            name: string;
        } & {
            [key: string]: unknown;
        };
        /**
         * @description The album a queue came from, so a controller can say what is playing without looking it up.
         *     As with `Track`, this is what a controller depends on rather than everything
         *     `atolla_core/src/models/Album.ts` holds.
         */
        Album: {
            /** @example 1c4e7a09 */
            artistId: string;
            /** @example Aphex Twin */
            artistName: string;
            /** @example 6f2b8c4d1e9a3705 */
            id: string;
            /**
             * Format: uri
             * @example http://jellyfin.local:8096/Items/6f2b8c4d/Images/Primary
             */
            imageUrl?: string;
            /** @example Selected Ambient Works */
            name: string;
        } & {
            [key: string]: unknown;
        };
        /**
         * @description What a player is doing. `idle` is a player with nothing queued, which is not the same as one
         *     holding a queue it has paused.
         * @example playing
         * @enum {string}
         */
        PlayerState: "idle" | "paused" | "playing";
        /**
         * @description A player in the group. Today a daemon is a group of one and reports only itself, so this
         *     array has a single entry; discovery fills it out at the step that builds the beacon.
         */
        Member: {
            /**
             * @description Whether this member plays. The enabled set is what defines the group, so a player that
             *     is present but not enabled is one the user switched off rather than one that failed.
             * @example true
             */
            enabled: boolean;
            /**
             * @description The stable player id, the same one `GET /hello` reports.
             * @example 4f3c9a1de8b27065
             */
            id: string;
            /**
             * @description Why this member is not playing when it should be, absent when nothing is wrong. A
             *     member that misses a track keeps its place in the group and rejoins at the next one, so
             *     this is what a controller shows instead of removing it from the list.
             * @example could not reach the media server
             */
            lastError?: string;
            /** @example Kitchen */
            name: string;
            state: components["schemas"]["PlayerState"];
            /**
             * @description How tightly this member can synchronise, as `GET /hello` reports it.
             * @example tight
             * @enum {string}
             */
            tier: "loose" | "tight";
        } & {
            [key: string]: unknown;
        };
        /**
         * @description Everything a controller mirrors, replaced whole on each read. A controller applies it and
         *     then asks again with the `version` it applied.
         */
        StateSnapshot: {
            /**
             * @description Which group this snapshot describes. There is one, called `default`, and it is on the
             *     wire from the start so that zones are an addition later rather than a redesign.
             * @example default
             */
            group: string;
            /**
             * @description The player that owns the queue and schedules playback. A daemon on its own leads,
             *     so this is its own id until a group has more than one member in it.
             * @example 4f3c9a1de8b27065
             */
            leader: string;
            /**
             * @example [
             *       {
             *         "enabled": true,
             *         "id": "4f3c9a1de8b27065",
             *         "name": "Kitchen",
             *         "state": "playing",
             *         "tier": "tight"
             *       }
             *     ]
             */
            members: components["schemas"]["Member"][];
            playback: {
                /** @example true */
                isPlaying: boolean;
                /**
                 * @example none
                 * @enum {string}
                 */
                loopMode: "none" | "queue" | "track";
                /**
                 * Format: int64
                 * @description The leader's wall clock when it read `positionMs`, in epoch milliseconds. The two
                 *     clocks are not synchronised, so what this is good for is elapsed time rather than
                 *     the absolute value: a controller takes the difference against its own clock as the
                 *     snapshot arrives, keeps it, and extrapolates from there. Reading it as a time its
                 *     own clock agrees with puts the progress bar out by however far the two have
                 *     drifted.
                 * @example 1758000000000
                 */
                positionAtMs: number;
                /**
                 * Format: int64
                 * @description How far into the current track the leader was at `positionAtMs`. The pair lets a
                 *     controller run a smooth progress bar between snapshots instead of asking for the
                 *     position over and over. Position is the only part of the state that changes
                 *     continuously, so without the pair the long poll would have nothing useful to say
                 *     about it.
                 * @example 91234
                 */
                positionMs: number;
            } & {
                [key: string]: unknown;
            };
            queue: {
                album?: components["schemas"]["Album"];
                trackIndex: components["schemas"]["TrackIndex"];
                tracks: components["schemas"]["Track"][];
            } & {
                [key: string]: unknown;
            };
            version: components["schemas"]["StateVersion"];
        } & {
            [key: string]: unknown;
        };
    };
    responses: {
        /**
         * @description Refused before the route could act. `incomplete_body` means the connection went quiet
         *     mid-body; `unsupported_api_version` means the version header named something else.
         */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /**
         * @description As `BadRequest`, plus `malformed_body` for a body that is not JSON, is missing a member, or
         *     carries one past its cap. The pairing code is not consulted, and the attempt counts against
         *     this caller's address only.
         */
        PairBadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /**
         * @description As `BadRequest`, plus `malformed_body` for a body that is not JSON, does not name a command
         *     this player accepts, or omits a member the named command requires. A member belonging to no
         *     command is ignored rather than refused.
         */
        CommandBadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /**
         * @description The submitted code is not the provisioned one, or nothing is provisioned. The two are
         *     deliberately indistinguishable.
         */
        InvalidPairingCode: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /**
         * @description The request carried no usable `Authorization: Bearer` token. A missing header, a malformed
         *     one and an unknown token all get this same answer, so a caller learns nothing about which
         *     tokens exist.
         */
        InvalidToken: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description No route serves the requested path. Answered before an operation is selected. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /**
         * @description A route serves the path, but not by the method used. Answered before an operation is
         *     selected.
         */
        MethodNotAllowed: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /**
         * @description The request used chunked transfer encoding. The daemon refuses a body whose size it cannot
         *     know before reading it.
         */
        LengthRequired: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /**
         * @description The declared `Content-Length` is over the cap, so the body was never read. The cap is 1 MiB
         *     for any request and tighter per route: 4 KiB for `/pair` and `/state`. `/command` takes the
         *     full 1 MiB, because a `setQueue` carries the whole queue.
         */
        BodyTooLarge: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /**
         * @description The request carried an `Expect` other than `100-continue`. `100-continue` itself is
         *     honoured, and answered before a rejection that would otherwise invite the upload it exists
         *     to prevent.
         */
        ExpectationFailed: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description This caller must wait before pairing again. */
        TooManyAttempts: {
            headers: {
                "Retry-After": components["headers"]["RetryAfter"];
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /**
         * @description The request head exceeded 8 KiB, so it was never parsed. Answered before an operation is
         *     selected, with the status line framed by hand.
         */
        HeadersTooLarge: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /**
         * @description The request could not be handed to TypeScript: nothing is attached to answer, or every
         *     bridge slot was in use.
         */
        Unavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /**
         * @description The daemon is already serving its maximum of 32 connections, so this one was refused
         *     without a request being read.
         */
        Busy: {
            headers: {
                "Retry-After": components["headers"]["RetryAfter"];
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description The handler was given the request but did not answer within 28 seconds. */
        HandlerTimeout: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description The route is in the router's table but no handler serves it yet. */
        NotImplemented: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /**
         * @description The handler threw. The daemon's log holds what went wrong; the problem says only that
         *     something did, since a caller on the LAN has no business knowing more.
         */
        HandlerFailed: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        /**
         * @description The version of this contract the caller speaks. Absent means 1, so a bare `curl` works and
         *     it agrees with the beacon's `"v": 1`. Surrounding whitespace is tolerated. Anything else,
         *     including a non-integer, is refused with `unsupported_api_version`, whose `supported`
         *     member reports what the daemon does speak. `GET /hello` is the documented exception and
         *     answers any version.
         */
        ApiVersion: components["schemas"]["ApiVersion"];
    };
    requestBodies: never;
    headers: {
        /** @description Seconds to wait before trying again, repeating the body's `retryAfterSeconds`. */
        RetryAfter: number;
    };
    pathItems: never;
}
export type ApiVersion = components['schemas']['ApiVersion'];
export type Problem = components['schemas']['Problem'];
export type Hello = components['schemas']['Hello'];
export type MediaServer = components['schemas']['MediaServer'];
export type PairRequest = components['schemas']['PairRequest'];
export type PairAccepted = components['schemas']['PairAccepted'];
export type StateVersion = components['schemas']['StateVersion'];
export type TrackIndex = components['schemas']['TrackIndex'];
export type Tracks = components['schemas']['Tracks'];
export type CommandBare = components['schemas']['CommandBare'];
export type CommandSeek = components['schemas']['CommandSeek'];
export type CommandJumpToIndex = components['schemas']['CommandJumpToIndex'];
export type CommandSetQueue = components['schemas']['CommandSetQueue'];
export type CommandAddToQueue = components['schemas']['CommandAddToQueue'];
export type CommandPlayNext = components['schemas']['CommandPlayNext'];
export type CommandRemoveAt = components['schemas']['CommandRemoveAt'];
export type CommandMove = components['schemas']['CommandMove'];
export type CommandSetLoopMode = components['schemas']['CommandSetLoopMode'];
export type CommandTrackId = components['schemas']['CommandTrackId'];
export type Command = components['schemas']['Command'];
export type CommandAccepted = components['schemas']['CommandAccepted'];
export type Track = components['schemas']['Track'];
export type Album = components['schemas']['Album'];
export type PlayerState = components['schemas']['PlayerState'];
export type Member = components['schemas']['Member'];
export type StateSnapshot = components['schemas']['StateSnapshot'];
export type ResponseBadRequest = components['responses']['BadRequest'];
export type ResponsePairBadRequest = components['responses']['PairBadRequest'];
export type ResponseCommandBadRequest = components['responses']['CommandBadRequest'];
export type ResponseInvalidPairingCode = components['responses']['InvalidPairingCode'];
export type ResponseInvalidToken = components['responses']['InvalidToken'];
export type ResponseNotFound = components['responses']['NotFound'];
export type ResponseMethodNotAllowed = components['responses']['MethodNotAllowed'];
export type ResponseLengthRequired = components['responses']['LengthRequired'];
export type ResponseBodyTooLarge = components['responses']['BodyTooLarge'];
export type ResponseExpectationFailed = components['responses']['ExpectationFailed'];
export type ResponseTooManyAttempts = components['responses']['TooManyAttempts'];
export type ResponseHeadersTooLarge = components['responses']['HeadersTooLarge'];
export type ResponseUnavailable = components['responses']['Unavailable'];
export type ResponseBusy = components['responses']['Busy'];
export type ResponseHandlerTimeout = components['responses']['HandlerTimeout'];
export type ResponseNotImplemented = components['responses']['NotImplemented'];
export type ResponseHandlerFailed = components['responses']['HandlerFailed'];
export type ParameterApiVersion = components['parameters']['ApiVersion'];
export type HeaderRetryAfter = components['headers']['RetryAfter'];
export type $defs = Record<string, never>;
export interface operations {
    getHello: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The player's identity. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "apiVersions": [
                     *         1
                     *       ],
                     *       "id": "4f3c9a1de8b27065",
                     *       "name": "Kitchen",
                     *       "tier": "tight",
                     *       "v": 1,
                     *       "version": "0.0.0"
                     *     }
                     */
                    "application/json": components["schemas"]["Hello"];
                };
            };
            411: components["responses"]["LengthRequired"];
            413: components["responses"]["BodyTooLarge"];
            417: components["responses"]["ExpectationFailed"];
        };
    };
    pair: {
        parameters: {
            query?: never;
            header?: {
                /**
                 * @description The version of this contract the caller speaks. Absent means 1, so a bare `curl` works and
                 *     it agrees with the beacon's `"v": 1`. Surrounding whitespace is tolerated. Anything else,
                 *     including a non-integer, is refused with `unsupported_api_version`, whose `supported`
                 *     member reports what the daemon does speak. `GET /hello` is the documented exception and
                 *     answers any version.
                 */
                "Atolla-API-Version"?: components["parameters"]["ApiVersion"];
            };
            path?: never;
            cookie?: never;
        };
        /**
         * @description The pairing code, who is pairing, and optionally the media server credential the player
         *     should use on its own behalf.
         */
        requestBody: {
            content: {
                "application/json": components["schemas"]["PairRequest"];
            };
        };
        responses: {
            /** @description Paired. The token authenticates every later request. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "token": "7c1e5a9b3d8f204617ca0be9352d8f7461a0c3d95e28b7f4016cad3928bf5e7d"
                     *     }
                     */
                    "application/json": components["schemas"]["PairAccepted"];
                };
            };
            400: components["responses"]["PairBadRequest"];
            401: components["responses"]["InvalidPairingCode"];
            411: components["responses"]["LengthRequired"];
            413: components["responses"]["BodyTooLarge"];
            417: components["responses"]["ExpectationFailed"];
            429: components["responses"]["TooManyAttempts"];
            500: components["responses"]["HandlerFailed"];
            503: components["responses"]["Unavailable"];
            504: components["responses"]["HandlerTimeout"];
        };
    };
    sendCommand: {
        parameters: {
            query?: never;
            header?: {
                /**
                 * @description The version of this contract the caller speaks. Absent means 1, so a bare `curl` works and
                 *     it agrees with the beacon's `"v": 1`. Surrounding whitespace is tolerated. Anything else,
                 *     including a non-integer, is refused with `unsupported_api_version`, whose `supported`
                 *     member reports what the daemon does speak. `GET /hello` is the documented exception and
                 *     answers any version.
                 */
                "Atolla-API-Version"?: components["parameters"]["ApiVersion"];
            };
            path?: never;
            cookie?: never;
        };
        /** @description One command, named by its `command` member. */
        requestBody: {
            content: {
                "application/json": components["schemas"]["Command"];
            };
        };
        responses: {
            /** @description Accepted and applied to the queue. The body names the state version that reflects it. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "version": 412
                     *     }
                     */
                    "application/json": components["schemas"]["CommandAccepted"];
                };
            };
            400: components["responses"]["CommandBadRequest"];
            401: components["responses"]["InvalidToken"];
            411: components["responses"]["LengthRequired"];
            413: components["responses"]["BodyTooLarge"];
            417: components["responses"]["ExpectationFailed"];
            500: components["responses"]["HandlerFailed"];
            503: components["responses"]["Unavailable"];
            504: components["responses"]["HandlerTimeout"];
        };
    };
    getState: {
        parameters: {
            query?: {
                /**
                 * @description The version the controller already holds, which is normally the one it last
                 *     applied. The daemon answers when it has something newer, or `304` when 25 seconds pass
                 *     without that happening. A version higher than the current one is answered immediately
                 *     instead, which is what stops a controller that outlived a restart from blocking forever
                 *     against a counter that began again; see `StateVersion`.
                 */
                since?: components["schemas"]["StateVersion"];
            };
            header?: {
                /**
                 * @description The version of this contract the caller speaks. Absent means 1, so a bare `curl` works and
                 *     it agrees with the beacon's `"v": 1`. Surrounding whitespace is tolerated. Anything else,
                 *     including a non-integer, is refused with `unsupported_api_version`, whose `supported`
                 *     member reports what the daemon does speak. `GET /hello` is the documented exception and
                 *     answers any version.
                 */
                "Atolla-API-Version"?: components["parameters"]["ApiVersion"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A snapshot newer than `since`, or the current one when `since` was omitted. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "group": "default",
                     *       "leader": "4f3c9a1de8b27065",
                     *       "members": [
                     *         {
                     *           "enabled": true,
                     *           "id": "4f3c9a1de8b27065",
                     *           "name": "Kitchen",
                     *           "state": "playing",
                     *           "tier": "tight"
                     *         }
                     *       ],
                     *       "playback": {
                     *         "isPlaying": true,
                     *         "loopMode": "none",
                     *         "positionAtMs": 1758000000000,
                     *         "positionMs": 91234
                     *       },
                     *       "queue": {
                     *         "album": {
                     *           "artistId": "1c4e7a09",
                     *           "artistName": "Aphex Twin",
                     *           "id": "6f2b8c4d1e9a3705",
                     *           "name": "Selected Ambient Works"
                     *         },
                     *         "trackIndex": 1,
                     *         "tracks": [
                     *           {
                     *             "duration": 293.4,
                     *             "id": "1a2b3c4d5e6f7081",
                     *             "name": "Xtal"
                     *           },
                     *           {
                     *             "duration": 568.1,
                     *             "id": "2b3c4d5e6f708192",
                     *             "name": "Tha"
                     *           }
                     *         ]
                     *       },
                     *       "version": 412
                     *     }
                     */
                    "application/json": components["schemas"]["StateSnapshot"];
                };
            };
            /**
             * @description Twenty-five seconds passed with nothing newer than `since`. No body: the snapshot the
             *     controller holds is still the current one.
             */
            304: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["InvalidToken"];
            411: components["responses"]["LengthRequired"];
            413: components["responses"]["BodyTooLarge"];
            417: components["responses"]["ExpectationFailed"];
            500: components["responses"]["HandlerFailed"];
            503: components["responses"]["Unavailable"];
            504: components["responses"]["HandlerTimeout"];
        };
    };
}
