/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/hello": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Identity and the API versions this player speaks.
         * @description Unauthenticated, and the one route that answers whatever version it is asked for: refusing
         *     discovery on a version mismatch would leave a mixed-version fleet unable to find out why.
         *
         *     The body is built once at startup and served verbatim by the server, so it keeps answering
         *     while the JS thread is busy. Every field is a process-lifetime constant; anything that
         *     changes lives in the beacon or `/state`. Takes no body.
         */
        get: operations["getHello"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pair": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Trade the player's pairing code for a controller token.
         * @description The code is compared by the server, so a wrong one never reaches TypeScript. Whitespace is
         *     stripped before the comparison, which is what lets a controller submit the spaced form the
         *     player displays. A daemon with no code provisioned refuses every attempt.
         *
         *     The body may carry a media server for the player to use. That is a Jellyfin token the
         *     controller mints for this player, not the user's own session token, so a compromised
         *     speaker costs one revocable credential.
         *
         *     Bodies are capped at 4 KiB and must declare a `Content-Length`.
         *
         *     Failed attempts are throttled per caller address. Three refusals earn a `429` carrying
         *     `Retry-After: 1`. A throttled attempt records nothing, so hammering does not extend the
         *     block: wait it out and the next wrong code is a `401` again, with the one after it held for
         *     2 seconds, then 4. A successful pair clears the failures behind it.
         */
        post: operations["pair"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/intent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Act on the player's queue or playback.
         * @description Not implemented: the body is read, capped at 4 KiB, handed across the bridge and answered
         *     `501`. The intent vocabulary and the token check arrive together in the intent slice, and
         *     until then this route is reachable by anything on the LAN.
         */
        post: operations["sendIntent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The player's queue, playback and group state.
         * @description Not implemented: the request crosses the bridge and is answered `501`. A query string is
         *     accepted and passed through, but nothing reads it, so the `?since=` long poll and the
         *     snapshot schema belong to the state slice. Until then this route is reachable by anything
         *     on the LAN.
         */
        get: operations["getState"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Format: int32
         * @description A version of this contract. There is one, and this is the single place that changes when a
         *     second one lands.
         * @example 1
         * @constant
         */
        ApiVersion: 1;
        /**
         * @description RFC 9457 problem details, served as `application/problem+json`. `type` is omitted rather
         *     than written as `about:blank`, which the RFC says is what an absent `type` means, keeping
         *     it free for a documentation URL later. Extension members are flat alongside the standard
         *     ones and are dropped when a given problem does not carry them.
         *
         *     `code` is the stable vocabulary a client switches on. `title` is prose and may be reworded.
         * @example {
         *       "code": "not_found",
         *       "status": 404,
         *       "title": "not found"
         *     }
         */
        Problem: {
            /**
             * @description The machine-readable name of this refusal, and the whole vocabulary the daemon can
             *     answer with. `internal` is the fallback body used when a problem will not fit its
             *     render buffer, which is a bug rather than a runtime condition.
             * @example invalid_pairing_code
             * @enum {string}
             */
            code: "body_too_large" | "busy" | "expectation_failed" | "handler_timeout" | "headers_too_large" | "incomplete_body" | "internal" | "invalid_pairing_code" | "length_required" | "malformed_body" | "method_not_allowed" | "not_found" | "too_many_attempts" | "unavailable" | "unsupported_api_version";
            /**
             * @description Rarely sent. Naming the field that failed tells an unauthenticated caller which field
             *     to fix, and `/pair` is the one body a stranger on the LAN can post. Printable ASCII,
             *     and short: the whole rendered problem has to fit a 256-byte buffer or the daemon falls
             *     back to `internal`.
             * @example try later
             */
            detail?: string;
            /**
             * Format: int32
             * @description How long to wait before trying again, repeated in the `Retry-After` header. The
             *     throttle doubles from 1 second and the limiter caps it at 60.
             * @example 1
             */
            retryAfterSeconds?: number;
            /**
             * Format: int32
             * @description The HTTP status this body accompanies.
             * @example 400
             */
            status: number;
            /**
             * @description The API versions the daemon speaks. Sent with `unsupported_api_version`.
             * @example [
             *       1
             *     ]
             */
            supported?: components["schemas"]["ApiVersion"][];
            /**
             * @description A short human-readable summary of the refusal. Every one the daemon carries is
             *     lowercase words, and it is prose: switch on `code`, not on this.
             * @example not found
             */
            title: string;
        };
        /**
         * @description What a TypeScript handler answers when it is not implemented or it threw. Served under
         *     `application/problem+json` despite not being a problem, because the bridge picks the
         *     content type from the status alone.
         */
        HandlerError: {
            /**
             * @description Which of the two handler failures this is.
             * @example notImplemented
             * @enum {string}
             */
            error: "internalError" | "notImplemented";
        };
        /** @description A player's identity, constant for the life of the process. */
        Hello: {
            /**
             * @description Every version of this contract the daemon speaks.
             * @example [
             *       1
             *     ]
             */
            apiVersions: components["schemas"]["ApiVersion"][];
            /**
             * @description The player's stable identifier, minted once and kept in its data directory.
             * @example 4f3c9a1de8b27065
             */
            id: string;
            /**
             * @description The display name from the player's config, empty if none was set. The whole `/hello`
             *     body has to fit a 1 KiB buffer, so a very long name stops the route answering at all.
             * @example Kitchen
             */
            name: string;
            /**
             * @description How tightly this player can synchronise. A daemon is `tight`; a phone joining a group
             *     is `loose`.
             * @example tight
             * @enum {string}
             */
            tier: "loose" | "tight";
            /**
             * @description The current API version, duplicating `apiVersions`' last entry. Short because the
             *     beacon repeats it in every datagram, where there is no header to carry it.
             * @example 1
             */
            v: components["schemas"]["ApiVersion"];
            /**
             * @description The atolla build the daemon is running.
             * @example 0.0.0
             */
            version: string;
        };
        /** @description A media server credential for the player to use on its own behalf. */
        MediaServer: {
            /**
             * @description A token minted for this player, revocable without touching the user's login.
             * @example 3d9f0c1b7a5e4826
             */
            accessToken: string;
            /**
             * Format: uri
             * @description Where the media server answers.
             * @example http://jellyfin.local:8096
             */
            baseUrl: string;
            /**
             * @description The device the token was minted against.
             * @example atolla-kitchen
             */
            deviceId: string;
            /**
             * @description The media server account the token belongs to.
             * @example 8b1f2c3d4e5f6071
             */
            userId: string;
        } & {
            [key: string]: unknown;
        };
        /**
         * @description Every length cap here is enforced by `pair.zig` before the request crosses the bridge, and
         *     an unknown member is ignored so a v1 daemon does not refuse a body a later controller added
         *     a field to.
         */
        PairRequest: {
            /**
             * @description The player's pairing code. The daemon strips whitespace before comparing, so the
             *     spaced form the player displays is accepted too, and it enforces only a 32-byte cap
             *     here: a code of the wrong shape is a `401` rather than a `400`, so the caller learns
             *     nothing about it.
             * @example 19524002
             */
            code: string;
            /**
             * @description Stable per controller. Pairing again under an id the player already knows replaces that
             *     record, so the old token dies.
             * @example phone-1
             */
            controllerId: string;
            /**
             * @description Shown to the user when they review what is paired. May be empty, but must be present:
             *     a body omitting it is refused.
             * @example pixel 8
             */
            controllerName: string;
            mediaServer?: components["schemas"]["MediaServer"];
        } & {
            [key: string]: unknown;
        };
        /** @description The credential the controller sends on every later request. */
        PairAccepted: {
            /**
             * @description 256 bits of entropy, hex encoded. Nothing types this, so it shares no shape with the
             *     pairing code.
             * @example 7c1e5a9b3d8f204617ca0be9352d8f7461a0c3d95e28b7f4016cad3928bf5e7d
             */
            token: string;
        };
    };
    responses: {
        /**
         * @description Refused before the route could act. `incomplete_body` means the connection went quiet
         *     mid-body; `unsupported_api_version` means the version header named something else.
         */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /**
         * @description As `BadRequest`, plus `malformed_body` for a body that is not JSON, is missing a member, or
         *     carries one past its cap. The pairing code is not consulted, and the attempt counts against
         *     this caller's address only.
         */
        PairBadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /**
         * @description The submitted code is not the provisioned one, or nothing is provisioned. The two are
         *     deliberately indistinguishable.
         */
        InvalidPairingCode: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description No route serves the requested path. Answered before an operation is selected. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /**
         * @description A route serves the path, but not by the method used. Answered before an operation is
         *     selected.
         */
        MethodNotAllowed: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /**
         * @description The request used chunked transfer encoding. The daemon refuses a body whose size it cannot
         *     know before reading it.
         */
        LengthRequired: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /**
         * @description The declared `Content-Length` is over the cap, so the body was never read. The cap is 1 MiB
         *     for any request and tighter per route: 4 KiB for `/pair`, `/intent` and `/state`.
         */
        BodyTooLarge: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /**
         * @description The request carried an `Expect` other than `100-continue`. `100-continue` itself is
         *     honoured, and answered before a rejection that would otherwise invite the upload it exists
         *     to prevent.
         */
        ExpectationFailed: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description This caller must wait before pairing again. */
        TooManyAttempts: {
            headers: {
                "Retry-After": components["headers"]["RetryAfter"];
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /**
         * @description The request head exceeded 8 KiB, so it was never parsed. Answered before an operation is
         *     selected, with the status line framed by hand.
         */
        HeadersTooLarge: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /**
         * @description The request could not be handed to TypeScript: nothing is attached to answer, or every
         *     bridge slot was in use.
         */
        Unavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /**
         * @description The daemon is already serving its maximum of 32 connections, so this one was refused
         *     without a request being read.
         */
        Busy: {
            headers: {
                "Retry-After": components["headers"]["RetryAfter"];
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description The handler was given the request but did not answer within 28 seconds. */
        HandlerTimeout: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /**
         * @description The route is in the router's table but no handler serves it yet. The body is not a problem
         *     despite the content type.
         */
        NotImplemented: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["HandlerError"];
            };
        };
        /**
         * @description The handler threw. The body is not a problem despite the content type, and the daemon's log
         *     holds what went wrong.
         */
        HandlerFailed: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["HandlerError"];
            };
        };
    };
    parameters: {
        /**
         * @description The version of this contract the caller speaks. Absent means 1, so a bare `curl` works and
         *     it agrees with the beacon's `"v": 1`. Surrounding whitespace is tolerated. Anything else,
         *     including a non-integer, is refused with `unsupported_api_version`, whose `supported`
         *     member reports what the daemon does speak. `GET /hello` is the documented exception and
         *     answers any version.
         */
        ApiVersion: components["schemas"]["ApiVersion"];
    };
    requestBodies: never;
    headers: {
        /** @description Seconds to wait before trying again, repeating the body's `retryAfterSeconds`. */
        RetryAfter: number;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHello: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The player's identity. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "apiVersions": [
                     *         1
                     *       ],
                     *       "id": "4f3c9a1de8b27065",
                     *       "name": "Kitchen",
                     *       "tier": "tight",
                     *       "v": 1,
                     *       "version": "0.0.0"
                     *     }
                     */
                    "application/json": components["schemas"]["Hello"];
                };
            };
            411: components["responses"]["LengthRequired"];
            413: components["responses"]["BodyTooLarge"];
            417: components["responses"]["ExpectationFailed"];
        };
    };
    pair: {
        parameters: {
            query?: never;
            header?: {
                /**
                 * @description The version of this contract the caller speaks. Absent means 1, so a bare `curl` works and
                 *     it agrees with the beacon's `"v": 1`. Surrounding whitespace is tolerated. Anything else,
                 *     including a non-integer, is refused with `unsupported_api_version`, whose `supported`
                 *     member reports what the daemon does speak. `GET /hello` is the documented exception and
                 *     answers any version.
                 */
                "Atolla-API-Version"?: components["parameters"]["ApiVersion"];
            };
            path?: never;
            cookie?: never;
        };
        /**
         * @description The pairing code, who is pairing, and optionally the media server credential the player
         *     should use on its own behalf.
         */
        requestBody: {
            content: {
                "application/json": components["schemas"]["PairRequest"];
            };
        };
        responses: {
            /** @description Paired. The token authenticates every later request. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "token": "7c1e5a9b3d8f204617ca0be9352d8f7461a0c3d95e28b7f4016cad3928bf5e7d"
                     *     }
                     */
                    "application/json": components["schemas"]["PairAccepted"];
                };
            };
            400: components["responses"]["PairBadRequest"];
            401: components["responses"]["InvalidPairingCode"];
            411: components["responses"]["LengthRequired"];
            413: components["responses"]["BodyTooLarge"];
            417: components["responses"]["ExpectationFailed"];
            429: components["responses"]["TooManyAttempts"];
            500: components["responses"]["HandlerFailed"];
            503: components["responses"]["Unavailable"];
            504: components["responses"]["HandlerTimeout"];
        };
    };
    sendIntent: {
        parameters: {
            query?: never;
            header?: {
                /**
                 * @description The version of this contract the caller speaks. Absent means 1, so a bare `curl` works and
                 *     it agrees with the beacon's `"v": 1`. Surrounding whitespace is tolerated. Anything else,
                 *     including a non-integer, is refused with `unsupported_api_version`, whose `supported`
                 *     member reports what the daemon does speak. `GET /hello` is the documented exception and
                 *     answers any version.
                 */
                "Atolla-API-Version"?: components["parameters"]["ApiVersion"];
            };
            path?: never;
            cookie?: never;
        };
        /**
         * @description Read and counted against the 4 KiB cap, then handed across the bridge, where nothing
         *     looks at it yet.
         */
        requestBody?: {
            content: {
                /** @example {} */
                "application/json": Record<string, never>;
            };
        };
        responses: {
            400: components["responses"]["BadRequest"];
            411: components["responses"]["LengthRequired"];
            413: components["responses"]["BodyTooLarge"];
            417: components["responses"]["ExpectationFailed"];
            501: components["responses"]["NotImplemented"];
            503: components["responses"]["Unavailable"];
            504: components["responses"]["HandlerTimeout"];
        };
    };
    getState: {
        parameters: {
            query?: never;
            header?: {
                /**
                 * @description The version of this contract the caller speaks. Absent means 1, so a bare `curl` works and
                 *     it agrees with the beacon's `"v": 1`. Surrounding whitespace is tolerated. Anything else,
                 *     including a non-integer, is refused with `unsupported_api_version`, whose `supported`
                 *     member reports what the daemon does speak. `GET /hello` is the documented exception and
                 *     answers any version.
                 */
                "Atolla-API-Version"?: components["parameters"]["ApiVersion"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            400: components["responses"]["BadRequest"];
            411: components["responses"]["LengthRequired"];
            413: components["responses"]["BodyTooLarge"];
            417: components["responses"]["ExpectationFailed"];
            501: components["responses"]["NotImplemented"];
            503: components["responses"]["Unavailable"];
            504: components["responses"]["HandlerTimeout"];
        };
    };
}
